#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage


#----------------------------------------------------------------------
pin00 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABX0lEQVR4nKXSz2oTYRQF8N83'
    b'mbYTOtK0lar4BxGqKBT6BC70IVzVR/BpXPg2rl0ogroQFxER0UIlxjT/M5+LSWA0kyh4NjPc'
    b'73Luuedc/hOhrvi1H2N/wvmYH2O6Q876nByFpf6kjmAw5XxKZ0xvzHBa1r/1Yvwngp1NGoHd'
    b'La7l3N0vOy/lywrSOoK9LITRLMZnLzntUBTcP6rrXEEASeDeAdsbzAq2Giv66orvvseYBEIo'
    b'XV5afB3Bl36Mi2nVhV994OmLGJ+34821KwxnjGa8PmWjwfVWmcqwyWBCkWlXuZcUdAfcbpGl'
    b'5CkXmxy26I5oZjy88nsSSwqOD0KYFDGmKZ8HJeHPfvn26E5IsKm0ZYai3pkKHp88WXh4GYe4'
    b'il00kayMcYE8vwDbuIXefGqBDmJtjBXcmH8fIJtPbc7/d1hzSHN8SpIE3iDHe0xVTuNvCrQ/'
    b'dmEfbzHxx139AgORanb3P7JwAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin01 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABDUlEQVR4nLWRMUvDQBiGn14S'
    b'TTiq4FD8BwrO7tIfITj6Lxxc1f8guAvi6uDqWCdd1Emwg9GkpRZNr8nduTSLvSQV8YGb7r3n'
    b'Xr4P/ovTOLd9ZexlWtiDu4HtXjxaV05UCTZDwUsOnwY0LYRoOXNOwd7Nq+2NpvTGmqeRoj+c'
    b'oFTB7tXbXAvfJUiSMbfa4C97TLKcwfCLlUgig+j5Z9bdC9g5f7DaGHzhsd6WbHVWOdxuz+Ur'
    b'BQD716mNAoGyS5x1ZW22kqPjE+f0Syq3UBKGUe19o6CJPwuca6z5zAcsYAD9G8Ea0AEKYAoo'
    b'IAM+FhVkgDc7etYgW6hBmrwDSCAA7svqJY1DjOMYYMP1GOAbXpVbXpaP7iYAAAAASUVORK5C'
    b'YII=')

#----------------------------------------------------------------------
pin02 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABF0lEQVR4nLWRvUrDYBSGn/za'
    b'tILQIYIIji7i6CTo4OSF6ODiHTgUf/AqvAHBveAgTo4tTi4FkRLamKZDk1iT49IM4pcfEV84'
    b'y/ne83wv58B/6X54LH7yLE/jjtz09uT0zhSVTy8CrDm7+PM+SRqQMUfX1VZN1bx6XJWt9X1M'
    b'UyeYvTHwXnj1hiw3m1wfzr7NmCrAKJjQyx6wbIM4jnkPQ5ZsG8syBrUSAJzcaiIi6JrGSstl'
    b'o73N0U73h78QAHDWdcU2HOJsQucgLPUW6vziUrn9XIVXyNVoOKXvlYAq/RmgPGPJZyYgQAak'
    b'vwG0ARf4BD6ABIiAaV1ABBiLShcJoloJ/PEIoAVYQD+PnqtyiZ7nAWyqhgG+ADRxVgGsWZYy'
    b'AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin03 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABIUlEQVR4nKWSsUrDQBzGf7m0'
    b'FEwrFGmtUMEx9gFcXcS9CD6Ag0sFJzcRJwWfxMndQfQNpIJ1cjAg2JZgakxM0tRzSTCI0YP8'
    b'4ODuf3fffXf3QUG07ODgKZKuGzB6mXCxsazlbcoi0s6lM5P7rRKbS3N0mgbr5w9SWWD3zpEa'
    b'0P+QjKYQxJ/fyv9QApi8+vSrZaQQjN2QZ9tHF2V1geHwjdtpjCYErh/x7kW05utKAgLgZtvU'
    b'bCdmZIfMIp21dhOjUlW8xA92rrzrXm9P6QFzGdwPigkAnJyeqX/jbzQaC8UcWJaVdaABetKU'
    b'EgrA4dGxBGrACtAGFoE6UEnX/Bm4zqoJECWnGkk5TGpAEqQ8oiBIBWrAI+Ap20/pdrckYObN'
    b'fwEwa1kx2UCJbwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin04 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJUlEQVR4nKWSu0oDQRSGv9lE'
    b'BGVF0RBECwkI0cZCBGsb68UnsI6+gUoqBUtBHyGlL6CQ2lLBdFFIlPVCdrPuxWQxGQt3YVFX'
    b'BverZs7M+c85Mz9kRCQ3tbsV6fo+5qtFdcMSaUlJtHhxY5/Kzbkaq7PblGbW2D3XpLLA2XVJ'
    b'CjTawQXd8J7+0ANySiPkAbqOS9Oqg/aB7Zk8220QQ3WBp46FHFyhaeC9O7wFLvrYJNBRG+HE'
    b'GIgX5xHTeiAIfRaL64zklZ7gJ/uXE/VKZeef2RGN20Y2AYDDo2P1b/yNQmE6WwetVivZgeDL'
    b'GDm+ufdP9g6qEtCBBWAeKAJTwGh8J3UEgOWlMkAYVR2Pwv0oBkRGSiPs9WIBHWgCvnL7MYax'
    b'JYFy2vknlGpd/PVmR4wAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin05 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJUlEQVR4nKWSPUvDQBjHf4lC'
    b'BY0YSnFRcFGqi6C4CfoViovgJLjVb6CIk6JfwMnFxY/hCziIczMICqb4Qs1JTZuQlpBz8AIB'
    b'TTnIDw7unrvnf/977oGCGNlFe/1EBkGAJz5ZfD4z8pKymOkkuriT1vk29tYqE0uzXJc3pbZA'
    b'c3lPAsS3jyQvgiTsgWkOzlQMA/gdn5EbBzOWhK0vvpvvkGgZ+BXwhEf80MDEIPK7BJ0upfEx'
    b'EJpPWBOXRvuthXj9IAxC7JU5TLRq+Jf76Z2ren1Xz38eTsMpJgBwdHyq/43/UamUizlwXTfr'
    b'wACG1NCv7v7BoQQsYAaYAiYBGyilZwa228J8FaCvbh1V4Z6KAaqR8uhHUSpgAU9AoG0/pVbb'
    b'kEA1b/8HE5Jd8DW/i5wAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin06 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABGElEQVR4nLWRv0rDUBTGf8m9'
    b'KQkiSCniKIgoKI669BlcHXwBNzfBB1DBwSdwcXVxdhIcBFcdHDpYuqTB2IYijQ1NjksziDd/'
    b'RPzgLOd+53c/zoH/0sfRtUw7gYwvbqW3ey73rX0x+ewigLO9gryGyCiGJMO2LaPP2H1ZP5Sl'
    b'9hZaaWJ/QNjp0u/7NFyPtn/1bUabAIPhkOzhCa00yeeEKIpQ2kEr3a2VAOCuuScigmVZuK0F'
    b'5jeW2bw5/uEvBAA8rh6I8hqk0Zid3mWpt1Anp2fG7ecqvEIu1/VK3ysBVfozwHjGks80IEAG'
    b'pL8BNIFFYAokwASIgVFdQAyoWaWzBHGtBO/hG8Ac4ADPefRclUsMggBgzTQM8AXv7FY0bHlw'
    b'KwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin07 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHElEQVR4nKWTO0vDYBSGnzYt'
    b'xktatFr8AQ6ddFXBXSgiLq7eJkUcvKxZVfwNRXBx7qjo/2gRh5QqKNVgekm+puY4iOBQaRLP'
    b'fJ73vLznHPhnJaI0n1hd8TyfxmuT66XpSCylF1+eu4HcfXzKxUNTlsuPApAMK5DVElgK6kpo'
    b'9wKMdILVcl1SYeC125pU3zvU9DR2p8fTW4eGo5jJZcJnsH5jiT6Uou31sB2X/KjBiJ4llAOA'
    b'ZkuwHRctqVHITVCYNDiYG44WZLG4Itv3LYkE/a7S5VV8uFKpxocBNrd2+gqEugPTNDfmFxbj'
    b'T1dK/Wk/1Bp39/YBNCDDt+sf54Mv8fjwSMay4wA6MAU4QAD4gDtw+tnpuQCzQJ4+3/sFRNVl'
    b'Bvok7NMAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin08 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABIElEQVR4nKWTu0rDABSGvxhr'
    b'q5bGDAYsuDqJOqr4BsVdcFBx8jJZBRcjTuorCCI4OLg4SDeLbyAOUloEQRDUhCZaAiat5DiI'
    b'4FBpEs98vv/85wb/DCVO8tnDuPhBgFV32Z55jcVy/bImbrMmd+6RXNzPyVapVwC6owr0qwa2'
    b'f4vTrOB/vtOX0ileikQS2C3r8ujeYPVUaPg2z84Tdc/CyA1Fn8FeOS/pVBo/8HC8N7IZDTXV'
    b'it6C69mEYYiiKOQHRhjWR5mfOI83yEJhVnauNIkF/Y7jk9PkcLVaSw4DLC4ttxXoigKbprkw'
    b'OTWdvHoQBH/aj7TGldV1ABXI8e36x3nnS9zcKEpW0wEywCDQAEKgBXx0rH6wfyjAGGDQ5nu/'
    b'AB1aZCGWTww7AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin09 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHUlEQVR4nKWTv0sCcRiHn7NL'
    b'A09DsCiCIggih+Zqapf+hMiooMKWamm5tRybo4Kgrf/CxZZwKl2iRSzpvO4s9Jt4b0MEDYZ3'
    b'9s7v83k/7y/4Z2hBkt+Wc6KUom5bzJVOA7G8H91I5+lVWtcFed46k8J4RgB0vwKhpEHnvkqn'
    b'XMVzmuiJKHlvVXwJFKe3xS0+EnmooCwHp/JCo2YRHUv6n8FdKivhSJjPjxaubTMYj6G3Pf8t'
    b'NGp1RARN0zBmJoilppi92As2yHR6RW4nNyUQ9DvOL6/6h0ulcv8wQGZ9o6tAyA9smubawuJS'
    b'/9WVUn/a97XGnd0swAAQ59v1j/Pel3i4fyDGcAJgCBgBXMAD2kCzZ/WT45wA88AoXb73C0e6'
    b'ZU/xGh8SAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin10 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABVUlEQVR4nKWSvUoDQRRGz+xP'
    b'jEl0MYpCggpWFnZprWJlCks7X8BSS4s04gNYCzZWPoNPIASC2NgENUpY3YhECWvcnWuRjUSy'
    b'CQt+1XA5c2Y+uPDPqLjhmaflSwu+Fr40mIAgdPyAk7XpP3esOEHWVFgKLAW2Al8LPQ2GPYrH'
    b'CgIRQoG3b6Hptrm/e8B99ph38vVEgr28oY4ee5KzjN9Z7bASW9eIGw4ybyvMlM1rszWWmShI'
    b'ksSCUvVcEgtqXZFNx+Lls0vXbbEwl8bM5Ni/vB6RjAhO3VAU8KlBpdLMFJaZXipi5xzq7gc7'
    b'F7cyUQDQCsAL+pyRSmHaNsow0aGGUANkgSn6OzY+x0+96kHDl92rRjWCV4EVoAgsAs5EAcB2'
    b'pSJAGigAG8B6dFZjKwzFKZe3AErR65no+7MDIHYTh9JRSgG8RxV8IAQ6gCQRSNvziOCbOOAH'
    b'5GpsNwyFed8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin11 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABXUlEQVR4nKWSQUsCQRiGn9l1'
    b'd01FM6PCoi5BHerUobtBkNcOUf2B6E8IUcd+RV06FHTrUpegc3RVKkKWFFdWQc3a2emyheEq'
    b'Qu9pGJ555nuHgX9GhG3eOgfKk2082eZLttAwQPm0unV2Fx/+nImECaxIGl2Y6JqJphl4soMn'
    b'O+iG6mNDBb7/ia88Wl0b+/2FUqmKXXFIxKzHkSoAXLyuq6iR+RWc7jihrDZIABC35jBMDdt2'
    b'BzJDBaNkZMH2kdn/goMEz51rtZTex22UcSsek8kJrDicXOb6JH2Cm8qeAkHXr6NbkkzWYHxa'
    b'J5oQFKv3HJ6PqaECAFcWaXhvAERMQcQAoYEnJUoCEAcsQB/a+6q8WTgrrarju5lCAC8A88As'
    b'MAWkhgoAtvJ5BUSBLLACLAdrMbBCT1K53AbAWnB7LBg/+QOEfuWeNIUQAG5Q4QOQQBNQowiU'
    b'U6sRwE9hwDfBDHNa82wNxAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin12 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABnklEQVR4nMWSvUtbURiHn3Nz'
    b'vfkgRm9TtZjaODgJCRjq0E0Xx4IIglM7dnOtYP+B4l/QwbaItIMgRhwdHexUpYNIEa1KhESt'
    b'Ntgk9+Z9O2hEYwxufeBwPnh/z+G8HPjfmPqDd/vex64W8xqU8yr89pX3SedOXQ375mYm56sA'
    b'RQHBIChR+97sbcGHgqioIgoCiIKFYe7L6sMErQFzeasqfQ582jpi/+cB3fHupgKrtphwjfFF'
    b'eWrD2h8h2hqhWimRP8k1FTR84MaF6Oq5sLH9i82175i/Z7TEE6xPjtyptxoJ5vP+7jPHIpFM'
    b'0O5GMZUi5dM8k0s/9EGCIdfuTQYNbU6AjkdBulIZQm6cb3tHvPy8qU0FswXRdMiQ8xRPlJ7M'
    b'c2KdnYRjUZ6EA2RfpSM3c3a94NgTTqsBfCBoGUJBh9hjl4tiicXRVC8QBypAAZCGTfx6IuoB'
    b'RpSdsrD+ZoyV5WwaqAL+1VwGDhvla4SBYWBoKbuswAtgEMgAKSDRLFyjDegHBt9OTS8AA0AP'
    b'ELm3B3WcXQ28cmkMGOfyp1/zD8VOkURaSyuQAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin13 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABsklEQVR4nMWQwUsUYRjGf7PN'
    b'7syO6w7urBaEpgWCS0kFexA92KFrBEGHIOoUlP4BJkLH9C/wVFHUIeySqwgiCIIeVKJDdhBi'
    b'F8o8uJKa6+zO+s3bIVeW3XXx5gMf3/t9PM+PlwfOWlrlx0Sm940duvIYwFVb5IqbPLj8tcpX'
    b'kl7+mPp9V3x8XNlGRCGawgzG6m5wDJjLPhERhaD+h0WhcY53E+9PBzCDznHwQijJ7NoL0uks'
    b'dtQCcicCAqWhz36pKd/D0ROs732ksdHisOjzdy9fd4Oa5WTcGVnbec339VWWV9L4B0FMR/Fh'
    b'wK/yB2oBljZHMnEzQWtbM012BJXXcf8IY6l+ORWgK/6w3TG6sULnaYnG6bhqEYkF+PZrgadv'
    b'w1IXML89KG3mbXa9Hyjx6LwexWkxaIgYxMOXGH/kWuU5vRKwX/hJrmEDhYcesDAMi6ZYmP0D'
    b'l9E76XbAATwgC1SXArC4MyxKPDQFW+4XXj2LMJ2a7AYUcHh0F4CNWvmSwsAtoP/zZEqAHiAJ'
    b'3ASuARfrhUuygQSQHHo+8gm4AbQC1okdVGj36FAs5O8B9wG/3PAPc06b10L1DZwAAAAASUVO'
    b'RK5CYII=')

#----------------------------------------------------------------------
pin14 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABsUlEQVR4nMWQvUtbURjGf/cm'
    b'anI1XsUUAxdRlw4VC7WIFAptZ8El4FAolI79B9qqs1uHjh1sh0ChmMGPluJSEbFIP1x0U4mL'
    b'0IhUY0xu7s255+1QIyFJg5sPHM4Hz/PjOS9ct4zah7OJN+/N/vhTAH2cR//O0bX6os5XUbj6'
    b'UnieEgKNuD6oACNkEuq1mza4BJRmPwsqAKWRQIMKEAzSb99dDRBK2P9CSmPcTJCZSpE5OqQ9'
    b'0tEUYFYOLc/uG1IqY/T14C/8ItYZw9MB536xKaDhcILvGfE+bLK79pPN/W0KYc0NHeHJ6ac6'
    b'v9kIkJ9KH4SHHPoTDna7TcnQnIjL1/FpuVKD8scfYjrduKkN1r9toPMuJ2enIEK0NUoyO3+Z'
    b'q2vgvV6R0Nggai+LuD53uwfotbroaLOIOnGS2XmrOheuBai9I1r+FDFEMGMR2mIW8WInBbfI'
    b'g525AaAH8IFjQDf8gj+3LvgKfe5R3jrgceELy0uLt4EAUBe7Bxw2ylcUBR4BDxeXlgW4B4wC'
    b'I8Aw4DQLV2QDt4DRl69m0sAdoA+w/juDGuUuFmWvlAQmAV1t+Atf+6RQT2fS6wAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
pin15 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABY0lEQVR4nKWTO0sDQRSFv8lm'
    b'3VVjQhSjqGhhY2FnZyH4aHzUViK2gp2FdukEG7H2L9hYJT9By2CRQsSARHzHZBPi6jp7LVyC'
    b'kjUGPNVwOPPNPXAH/ikVZr7tZ8R3XPzaK+K4CICneS9V6cts/7gTDQNE+uMo20TZJr5lIlUX'
    b'39OYRnM8FCBvHvKu+Sg8cp8vcHl3ze3LA3bUzrUF6NicVZXlQzEG4g1vo5INrRsJMxv08RSW'
    b'EaVYefw10xLQjtoGHPQuSNsAfXYlnWvT1C5uuPOqxJNJYsoku7LbBGkC1HeOBQU4dWwijFgJ'
    b'Bs0YPcqidJrnZHBVWgIApFjGvy0D0KEMLGVgKIX2NVoEoBuwAKNl79r6Ubo0sye5ia10EB4D'
    b'RoFhIAUkWgIAFpeWBLCBIWASmAjO6tcK35SYm5sHmApe7wrGb2xY6CZ+k6OUAigHFVxAAw58'
    b'/bG/APL89EQQPg8LfALeym+ZtHDexAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin16 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABmElEQVR4nMWTMU9TURTHf+fe'
    b'175qiTxsbSAKs9E4IaM6+RF00Di4mxg/hAmjDg5sDKzERAfjKIaEgU0NQWvREEptGwxNfe2j'
    b'793jwGOgvCKb/+QMN+fc3zn35H/hf0tGJZb2nIaJ8idRQgdhojyfzp2oN6MAZav4VihYoWCg'
    b'aOFVY6BPNrp6JsCeM1QsFIzgG8EToRlDMJY/2wQPJkQGTql1I2pbdXwjFIwgQ6/2RgEAnAgY'
    b'j+32PmvrG9yolFi4N3uMkDnBu47ThVai25HSbLbZ+lJl6sLlxeHLJwDz9VhrkepMTrh2ztCJ'
    b'Hb9+1LE2z/Kj64+zmh0DlPKGnQFs9pXVTkL18ydaOw0mxsvMvXiv/wSMGwm+R8rPyNFzin/p'
    b'CkE5oLVb5WalCGCBXBoWhpZ4/6LsA/KyEWvklF54wCCxcD6gZ4oAk0Ccljugm7nEp5OefH32'
    b'kABHv3+ANRYjHoDPoXt/A22gl2nljx9W9Nad23fTYzQUHaB+VJvpg9dv3gJ8A6aB3XTcGAjT'
    b'7qfKAFeBEqd8tiP9Bcujk5JdYbsQAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin17 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABq0lEQVR4nMWTvU8UQRiHn9nZ'
    b'5XCX8+AOFROPoA0klFKCJiYW2lpoYozhf5DWWlsTOgpLpTFCQULHRyKQ4AcmJojGU8J9cJfc'
    b'F3i7e7MMBUvBsYd0vslbTOY3z7zv752B/x2i3cZiZUL7qoKvqviqhqfKPBxYPaU32gESoh9L'
    b'dmFJB1M6xMwk89mneurboD4XoM4OCTmAKR0saSONDmoqw0U7db4KRhMvRBC4FKtfyPzawpQ2'
    b'lnQQLU2Y7QAA2ggQhiZb+s3Kp49cv3ST5w8+nEBEmvi5/kqX3K+ogwY//6yxvPyDZO+F15NP'
    b'9sdbtSdaeL9zX+e9VZ0yh7nmjNFoFtneriAERB0+BeiKpSmrTfLuCpvlt3zfyFDI1bHjHTye'
    b'RP8TkDC6uwveOkVvg2ZQJ35Z05O0qe4qhnrvAEjAClNCi4kjyZdVQMzlHmkV7NNwXZRuYjoK'
    b'z9gF6ANUKD8A9iLHeO/qGzH97Aad4gqu52MIgcYHiHFkfBkoAY3IKSwtLOqx27fuhkuvJWtA'
    b'9lgb+Q7ezcwCbAFpIBeWq4C/4e1nhgEMASnO+GzHcQi6BpsTj4qJlQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin18 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABq0lEQVR4nMWTP2sUURTFf+/t'
    b'jMm4mdlkVjSN2GwhpEulxWoVCFimswsp7AJ+Az9AKis7RYiFIEJCqjT5I4KISxCyRtIkwczu'
    b'wsR13cnujjNvnoWjJM5uki4HTnF55517uO8+uGyIQQfRszWtjgKSlMpvU1h5nNHLQQZ6LI90'
    b'LKRjIRyLXNEmmF/U9TtP9EmdMTBa0ENfdxCRQkYxSRSjaj+w3MLFEphzZaGDHsfvvrL/cRth'
    b'W0jbQhi5U7qBCQDkFRMjAf+gRuVTBXeyxPTqwqk59DWI3lS0+uIRVw9peHV26nuMDdsvplcX'
    b'ZjNNThbB3HOtdhta3nIx75aID5vsNxtIYKb+OnM5Y2CUbqD3vhNvHdBdfM/nnW28ls9V0+Jl'
    b'4YE+12DINUeT6jdU1SNpdRgXeYp5Bz9u45YnAHKAmTKXmYF4NNUCxPH8K63bPcJeFx0pRhID'
    b'edQBGAfiVJ4AQd9nzD99KGbtD+hrI4S/QoQQECqAIf5sbxPwgW7fVd5c39Dl+/em0jL8jz8B'
    b'79/c+hm8XVoG2AVuArU0bgx00u5nQgK3gSJnfLa/+A2AQaGDMwJNRwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin19 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABcUlEQVR4nMWSTS8DURiFn3dm'
    b'Wu2Ij1IRSdlIuyIhtZBYk1j7C3bs/RkbP8BGgqUNiZ3YICipj6JCTVM1mTuda2FI6YjunOTk'
    b'JjfnfXLumwv/LYm63HYCXfE1ZR/qDf1h1aDqvLE6mfo2Y0UBqlrwgLhofAN8Db5lkEjGWrJG'
    b'FGDGhpghxA0hLqEN4eqk0pKNbPDggwo0ZS+gXFeUbirclV7o7uiaaKtB3hYZSwo9Jrh1l9uz'
    b'C0b702wuDB+2BfiUAIgggG1GZyIBW06gw9nQQsKC2bU9/Sdgp6b1vQ/XCrzgYxgxKFYVJor5'
    b'jcI3SMsSR2JQ8uBRabQImVQnqbkpXl2F44xjv6k/GlQDsh3CtA2DFvRZMBQTno6LnB6cM5JM'
    b'AqSBXsBoASwOmAKwW9MU3IDTms/+5TO3rx7A+spUTyaMukAQtcNmZZaWljUwDeSBMSAL9P36'
    b'hB9S2VwOoBOIhzaBxmcg8ic26aHpPAJ06C+9A06bggSnTWkKAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin20 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABmklEQVR4nMWSv07bUBjFf9d2'
    b'YseUBhVEQYIB1GSiUlEXJiSkrnRgY+IBKGLsY0AfAHXqyFSpr9FWJRFDwn8QoYTi2I7j6zi3'
    b'A6EEcquy9UhHV7o65+h8nz743xC6z2/+BxUk5zTkHrLtIdMGLdnACwLWZg/ueSxdQKR+0ibE'
    b'Mhw6pqSjErKWxLWTPq2hCyg6y5iGg2nmMI0cluFgmTlK1f0+rbaBl1ZJ0xg/OsALjzmp1Ti9'
    b'uMS2M68e1WA691ZMugu4mec0WzH71V+MDI6xsZh8f1TAHQRC3NCx8lqFNuCrt6m6doQAIQRZ'
    b'8wlrnwbVPwNK4Za6TivUkxJtFSGEAAHnfhmjk+X9F/deSN8Sh62XXCW7NOQhCsXo0DRv5odp'
    b'xh7XfoCIJ4C7VfQ1KPsfGbfnKLhL5DNTDGTGydtTHFXa/Ng54anzAmAEGAIM7SVWom21538m'
    b'lGcE0Rm1+hVHx3XCptzeWlHrQAwEQEvn78XE6uo7BcwBr4EZoAA8++sID5AUikWAASDbpQmk'
    b'twLtJfag1vOWAdXlH/wGUpeVeC4O7UwAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin21 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABrElEQVR4nMWQTWsTURSGn3vv'
    b'JM3E6cQkFqybiht1I1KDH0jFvVs3ggh+/Qrd+hd0WxHpTygiLVU3CkK7CXXhJsWStmiTzLSZ'
    b'mU7mHhdWaeswuPOFA/eec+/DeV/431JHG0/X0uUkyy4OwphwEDM3c/KvN7mA51uZRFaIMiG2'
    b'MEwzdsKYMCiGOABzPZHYyoG2QMnAeIV6aAstOABGQUUr5NBIaK90GOlqIeDPapupyJ6FT0Ph'
    b'4yClu95no9tn4fbZwgz078PnodBOhLXEUtaKYKNLGu7wcHFX/glwq6bVh/6IS57BNQr/RIMk'
    b'ibjQVFx7sSQzr9u5IH3wcsV3OG6gahR+3aMyZnjX6dGcOo02Ou//rxABXm1b6abCdgaTJc1W'
    b'zaN1c5owiAgGEWrPFFuYKitco4itsJla/JLGdTRNv0Jn9StxtFsMuOEpNeHA3YbmqqepaQjj'
    b'lM56nzHX5e2dc6eA8cIMviXCagIrkRBYKJcdel+Wnyzda50HjgFNoJ6bAcDjCaOAKnAZyF7O'
    b'zr5v/Pj+bB7eAKP9yvdyRJNAC7h+/8EjAaaBM/tbHNJPakKlawZL0hUAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin22 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABwElEQVR4nMWQP2gTYRjGf8l3'
    b'd/Hyv7ERKzhYpKU4VKuD0grOggiii4tWXNzESSnOoji46ORghy7tUMRJEYTiXhGKVo3WaqRN'
    b'e9TL3SW5++7yuaRYbZK6+UzP974fP57nhf+t2N+D6a/H52XYOGy7Vaqux83R1W1/2gJeVC4r'
    b'GTkEkYOMHHzp4njejhAN4LV9S8nI2b5NgXT2AqsdE2gAIqaByLRGCtVy828/47PYrcHvCj/D'
    b'kgqbdUq1GT5Zs5Qra/yorPPgrOx6g/im+VJ7Rtl/xXp9AU3swlrxqVUjbr/MqX8CHMlej723'
    b'pujPnEEXWQoFExk0GSyeZvyxUNdmaAuKb30czJ/D1PZgaFly+RQJw+DNt6f07U8i4u2baJtm'
    b'buOG2gg/4tS+kzcGcLJLjJ0YpOp62K5LI/CBoHOCYmIYXaSRkYctS5h6EUNP05Pp5cPiGn6j'
    b'2f0GQ8lLsZw4wFjhHgPp85iiF69hs7yyjGlqPLwQ7gMyHQEAlr9AOZhjqf6cemSR0HXK75oT'
    b'jy7KISAF7AZ62kbZoiRwCjg5+WRS3bl7XwFHgWHgEFDcCQDQBxwDRsevXFXACNDfSvGHfgH6'
    b'4amVGARHIgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin23 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABvklEQVR4nMWQO2sUURiGnzmZ'
    b'2ZjZzWYmcTEqCFoEFyGGRCsNWBghgggWWiv5AfaCrQgptLEMEbFQGxs7RfCCaKFFSLJeEDE6'
    b'kBmNM8Oc2exlzrFwg1HXXTvf6rvx8L4f/G8Zvw+iE1dfZcn6mIxjpJTsrVz546YtoHrxrtah'
    b'RH1LUWFKM0qRMukKMQEac0+0ClNUiyhaizyata0mVP7uwAQwLBPh2K2RRukfoKXXi6gw7ZTg'
    b'ZwTlhZp6k+b9ZeSNp/jBKn7gMxnc7PgDsVFkj9+SvfxIc2EFYef4nEaEWZXnu2b0PwGsMweN'
    b'dO4RuelRxGCeUqFIPctwjo1xZ/CkfuCebgsSm5stpyYQpX6EW2DALmLlcvj3XrA7X0IY7ZOY'
    b'G0X92kOtvIhG/IaekW0UKx6Hy+MkMkEmCWltvXOEnpFhhNOHjquo9wHmThdzwKYw5LK0+oFa'
    b'1ugCOFo2jGGH3vNTWNOjGI5NbS3GX/lEn9nL1NdbO4D+jj/Ilj3Uokf27B06qmJZORbqwYXj'
    b'X26XgTwwBLhtrWySDRwBJq/Pz+tLl2c1MAHsB/YBpW4AgO3AAeDQ2XMzGhgH9rRc/KLvhk+q'
    b'5Ld5zIQAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABkUlEQVR4nMWTT0tUURjGf++Z'
    b'O3PBW+a/QVCxLGZIciG4ESEKP0Hrdq0N/Bh9kWiltGlT6zZCKAOVMYoOIl5vd5wZ8gxz/809'
    b'LZxMnVu684GXA4fn+fGcFw7ctiTrMlnfNInbJN3zSRtt0kabuKnR+pT7W28uZaxMbDtEJSnG'
    b'sZEwQcIYK7Sx47jPqrLy6lkZGSigHBvl2Ehvqns7fd7MBsZtkeqA+IdLZ9flp+fh1T3yVmH+'
    b'Rg1yi4/EWiqhxgcJwoBq4xC7OMxT/23lRoCzGgaUgAiCkB90Mm2ZgOjdhgHOw4iQu2PzYfKl'
    b'uRbQ/fjNGLeFqZ1AGCM9iN4+JMkrNiZeXYL0LVEejKJqdZJ9HxDuPZ7meXGYqKk51b/o3M3D'
    b'0X8aRGtfUE8msZZnUdOjyMQQ1kyRauBTOdhBPRwDGAOGONtSv7qfd0306SvJvk9U8zlp1Dnw'
    b'j9FRZ/1F6/0qEAIaCLLyFzW1svLaAIvAAjAHlICRfz7hiuJSuQzgAIXe5IDuH0P2X/gr78L5'
    b'HTC9OddvdeuTZlfAswgAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin25 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABnUlEQVR4nMWSvW4TURCFv9m9'
    b'VhJ7rbB2BFhGyA2RIhoCBRVNeADo4BmQQBS8AHXEEyAqREMFHQ0FFURCghQICURQ+ImRN/6J'
    b'7F2vfXfvUKyUzmw6RjrVzHwzOjrwv0tOMvR04LRdgZFVdhPHw3OV471SwIsj1cTBJHNMci2U'
    b'KcNhwuNLp8QrA/xIHZ6AJ1II8AR843HrTVdLARerHoEovoAP+CL4IhjjYYxHKeB6XaSXQXfm'
    b'+B5bmgbWjEAUs5TWO6YMAHBhSfg9daSp5dVeRNQb06it8vJGdX8h4PlQdZQ5coW+VVIHB99+'
    b'0o8S1jsbPNmqCcBCgKMwruZD1yqT2ZzJKCYIQj5/eX88t9CDNVM0D60ysI7xYEwyndFuhIjm'
    b'XHv2Sf/5QehDbKBlhA+5cLbVZKUeMOjHBK3zZKkFWJyDK1WRrlU+Jo6RdeRHMaeXfVpVQ1hZ'
    b'4fXtjTbQPEmUm/e/JodRb8zB3i/s3HFzc50Hl1c7wJ8ygPdoezuvLNe4d/fOFjAD5kAKTIH9'
    b'0vNv3+0ocBU4AzSAEAgogslfu7GhwPDwV6cAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin26 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABrElEQVR4nMWSMW/TUBSFv+fn'
    b'tnEdWtGohLQVdEIq6lCxdEOiYkFiRGJjQQyAYGFmQmWp+h/YGJCYqdjaoUVMDB0qQKlRRUlK'
    b'nmM7dvyeE5sBKVtwN+5y73DOd3WkA/97xHlEu90XRU2ukGQtvN4O967sjnylgM/RZqGHIelA'
    b'oTMfPVCkmcIPA56uNYVVBugkhwhhYwkbS8jRbUvJ6735ohSwNH0LR8whRua/W0qJbUtKAasX'
    b'HokgaxIk3zkLv1C1F5mZWKLnTxEk6bJdBgBoVNbx4yNSY9g7fE9bKZzKFNt3tTcWsB+8LOKs'
    b'RZ5n9LITsjziuNmhrbpcXpjl1e1AAOMj5AwRwsKZnMc3X+mnEWGU4riSn1480o0FzFhXEUh6'
    b'+gexOaEbxCRpn9rsJYpc8PgdBcDYCK7dQOddbHkNb/CBRr2OW52k4wfUFiRGSyAV/yzSx7OH'
    b'RWJOifUpJp7GdRz8MMJrfWPzTmcRMOepcu3N0fXfbaXwPIU2A26u3ufBjbfLwK8ygLW9tTWc'
    b'qLg8f/ZkA9CAAVKgD3il7/cPPhXAOlAH5oCLQBWQAH8ALymvmgDhG/YAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin27 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABrklEQVR4nMXSv27TUBTH8e/1'
    b'sd1Q2tAkQBIqIsRANxgzFCRgLwviJUD0EZgQS8XMwoCEkEDqI7R0qgpCAqRCBhCF9F8UN8aO'
    b'29SxY+cyAN1Ss3GnM5zfR0f3HPjfT/1L0+DJiqY6RdryiZcb5BfvHeUygeTlO633Q1InYOgE'
    b'pO2A1AkIfJ/a+0fKyALiDz9QlqBMAVPgTy0iNC7N60zAvjqDztm/g38hSxAxEREyAXPushpu'
    b'uQzWtzhc/YJROYWcK/BTIjph94KZBQDIlRrRx03iOGL71RKu52LZY1xrP2+OBAbPVnW646Hj'
    b'hOGuh/YP2djbxfVcypNF6ptPFcBIQAHKNDDOFEi/OUTdA4LwgHGx2e65R32j/6A4AWKQfG2T'
    b'Njt4vYCwH5I/WyIFlgp39PETlCdR3RCzMkW8/JlKtUrePoHf9alZefo6ARh9B1K/qIbfHeLX'
    b'DZKmy76OsKZLjJ0/jR63ud5+MQ2Ujt1C7sEtBZT2Zh92ei2XT50WURIzc/sGbGABbtYpG48X'
    b'FlIrd5L5+3dvAhEQA30gBJoZeVh781YDdaAMFIECMAEIwC8Br6hYrdVd2wAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
pin28 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABz0lEQVR4nKWSv2tTURTHP/f1'
    b'5fWlYKsUFAS1IS4O1UmCiFAQXUTI4iKI4OzgX+Do7ipOojgoQjIVFHWUiqE6qahgLWlJWhrT'
    b'd+/re/eXg6mYX3XwLAfuOd/v+XDugf8MMa5gjPHbSYIQAmss09P7KBQKQ/3B4EOtVnvVXFv3'
    b'20lCPDlJMY6Jooitzk++r/zw/zSYnz+5IIQgEILbzxtcur/It80uQgiEgI+fPveZhIPTnXM4'
    b'a7n5ZoUr5yockJ47X9usfljm0eXjOOfGExw5OregjSHXmtlymZYGhCcIAoqHjqGNwRhLvV73'
    b'Iw2azVXyXJNlGWozobGR8mU9odNRVA7PkGU5Wud9BENbXXr7zkdRxJONIktdj9aWYhhz73RI'
    b'q91mJ8s5e6byRxcOGqRpirWW6ozmxtx+SqUyjeX3NNcsea7J82xvAoAXL1/7cGKCIAgQIsA5'
    b'i3UOozUXL5zv0wx9I0DS7dxSKkUphZQSpRRKqSHxWINqtXpXKomUCqkkUimUVCOJx54ywIOH'
    b'jz2A957r164eBHJA97KFEUv8O8Lwd3kqjgCmgEJPHPZyNk67G/HTZzUPnAJOACVgFoh26fck'
    b'AHaiKKLX3AK2gL5b/gUiANKui5R0JwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin29 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB10lEQVR4nKWSTWsUQRCGn+7M'
    b'dsaA8QsDBlaz3nKIoiAiUVgMCoLCHkUQf4JC/oH/wIMHD15ECIgos1clUREFRVHwoBIUY1gl'
    b'QTab2Wl3pnu6PbiKu+vEg3UpqKr35aGq4D9DFDWstT5utxFCkNuc0dHNlEqlgXnZX4iiaKHx'
    b'5auP223C4WE2hSFKKZprLT4tffb/NJia2lcVQiCF4Nq9s1y8Ps7ytzcIIRAC3r577wsNoiha'
    b'cM7h8pyrTw5w7Og0p04f4u7SGWZv7cTlDudcMUF590TVWEtmDON7Q1r2A+CRUrJll8BYi7U5'
    b'9Xr9N0Xwp0GjsUy5vAchBOstx6KZp5OmNOOYybEqaZphTNZDMLDVZ89feKUUT5uXWYzrGGuR'
    b'UjJ78CMrq6t00ozpI4dFocHDR4+9UoogCNi+bSuVygQvX70mtzlZZsiylJnj1WIDgPvzD3ww'
    b'NISUEiEkzuXkzmGN4eSJmR7NwBkB2utrl7T+jtaaJEnQWqO1HhAXGtRqtSuJTkgSTaITEq3R'
    b'if4rceErA9y4OecBvPdcOH9uDMgA08059J2xP4LgZ3skVAAjQKkrDro53UgPEN6+E3lgPzAJ'
    b'VIAdgPpFvyEB0FFK0R1eAZpAzy//ANOZyTyWSULIAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin30 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB0UlEQVR4nKWSPWtUURCGn7m5'
    b'e7IuGjSilatZRUEwWkowyGrQ1q3FEPAX+Av8AQqCpa0IQhDhbiERxKhooxgVi6iVX6whKbLZ'
    b'7D3m3vNl4Som642F0wzMzPvyMDPwnyFFDWttWO12ERGcdQwNbaNUKvXNRxsLSZLMtr4thNVu'
    b'l/LgIFvKZZRSLLdX+PT5S/inwejo0bqIEInw7OJVpg9N0p7/iIggAu/efwiFBkmSzHrv8c4x'
    b'X7/MeP0k58ZO0blwg/sHp/DO470vJqjuHakba8mN4UBlF2FhBUSIoog90VaMtVjraDabvyni'
    b'Pw1ara9Uq/sQEazTmHtzZFnGaqfD8PgRsizHmHwdQd9Wn794GZRS2GszZDNvsdaACPtfXWFx'
    b'aYm1LOfE2HEpNHj85GlQShHHMcM7tlOrjTD3+g3OOvLckOcZE6frxQYADx4+CvHAAFEUIRLh'
    b'vcN5jzWGs2cm1mn6zgjQ7bQvaf0drTVpmqK1RmvdJy40aDQa11OdkqaaVKekWqNT/VfiwlcG'
    b'uHnrdgAIITA1eX43kAOmlx1sOOPGiOOf7UpZAVSAUk8c93K2mR6gfOduEoBjwGGgBuwE1C/6'
    b'TQmANaUUveFFYBlY98s/AM7RyHLAiPbEAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin31 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABsElEQVR4nKWSPWsUURSGn3Pn'
    b'zuxmFRIIkkpBERRtFgwEqyBKBAsLUdDO1s5G/An6J4SAglWsBLu4pBRBsJAgWlgEbAJhMTs7'
    b'9+tYzK7uuJM0vnDg3nPPx3M4F/5T0uZ8+l0Xb51KBx8OFSPgEtxeMlzumbn4OceTH+7TgpH+'
    b'SSssWsGK8Csqw5A4jMrzM0Ujx7QA9JH6IROhMPV5mvX4W6mzwXb28ujLcF1ViSo4hWdXziEi'
    b'GGN4sLNLUkgpNbo1CKJPA+8jPikvrp4ns5ai06Hodtna6BOTEnzi4cf9960EzkeyKvzpavOc'
    b'vCiwWQYiVJXHucDm6vK1VoLN1WUZjz1l6bj57jPWWvI8Z6F3grWXA8alp6pCY4QGAcC49MSY'
    b'8HnG2qsdQEiqjEYO7wLONQu0/oO723tqrcGYGlBViTERQuTNjdONnDkCgHLkyDKDGEGmBZIS'
    b'fBz8G9tKAHB966saERDQVK9v+96FDGjs8cgCAOuvdxUUEWFw/+IK4CbmgXDkCFP1ii6gIALQ'
    b'A/KJOaCa2LHq3Hn7U4E+cAk4CyzNNj6WAKhqCiKwBwxrpL/6Dfk/qlSBBe+zAAAAAElFTkSu'
    b'QmCC')

#----------------------------------------------------------------------
pin32 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABtklEQVR4nKWTO2sUURSAv3Mf'
    b'u2MCGohioRYBK0VZTDqLYCpLwcY/oBYWRiTYBgRrLSwsFbEQ0gSCpWsfEaxETBWsxBBC3Jm5'
    b'TwvXMONs0njgFPc8v3PPvfCfIpOMb7fmT1w6eX/32681RDQxlczPrHB2eqkT3zG82br8yZrj'
    b'g8LOUthTaNWj9juU/gcu7HJr7mMrR3WZZCAiiCi0smhVIKIRUYDw8uvF3Aw3zcOLz+cXc86k'
    b'5Amx5PaVd4gISimeDM+QicSUWv1aBDGnoQ+BmGoeXv2CNoZev0+vKFi9/pMYAyEEnm6eez+R'
    b'wHmPVuqgq7EW2+thtAYRKreP857lhe1rEwmWF7alco5RVfFow2KMwVrLsalp7r7ao6prKuda'
    b'I7QIAMqyJsSINYY7rx3CPilnRlXE+YBzvn3nnS0Ajz/MZqM1ShSiIKVMjAkfIqtLO62cDgHA'
    b'qKzRWqHkz4Q5Z2JK+BCG/8ZOJAB4sG6ziEIaBZ7dCBpo7fHQAgD31uTg0Ty/mU8DbqweCIeO'
    b'8Fesabr9FGDH6oB6rEdKf2WjyMAAuADMATPNxkcSAPWYIgLfgT2g9Rd+A85yqgL+4Lo1AAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
pin33 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABP0lEQVR4nO2SPy+DURTGf/d9'
    b'36oqCaISLBKJSETCXGETu8H3MJD4DGwWidHsE2CRtItBB7NEpCVa/1X0veccQ18JWowWz3JO'
    b'bu7zu8/JPfCvv5f7erByXLWbF89Tw5NLBXQFsDk73HKvBbB9LXZy9Yx4xYs0a6yIKAMRbOWH'
    b'2kKi9+asLmSzaUQU7xOAKOKVTPjLCBuV2MSaD8RqvKjRUMP7JuCuVkcfw+ndxf5S2wQ9YUCH'
    b'A+cgVqir494br4FDOkJOS7ccLI+3mAECgEpD6U85chEMpBx9kaM3FdAZOkqlCxZGu38eAWD/'
    b'QS3f7Sg8GWLG4b1QrT3DQ52d+ZEcIEAMvCb1MwDgvGF2GRtHj4oq7C3NUSwWxhKzAD4x3wD2'
    b'Xao0MAnMlMsVA6aACWAMGOTDz/2mCMisrq1bAm27B2/03JLxzrLXcgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin34 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABT0lEQVR4nO2Sv0tCURiGn5v3'
    b'mj/QhigCxQYhgghqsqW9tSBoa2kJ2oKCZv+DtoKGpv6AxpYacqoMkixpVchbXa9iXu8597Tc'
    b'JNNsbOmFw/k4nPfh/fg++NffS/v+cHCVUXbrmWbbZsRIEtRH2Fy46PnXAzgzN9RT5RwhZdeR'
    b'QhIPJtjK3PSF6J9FtX5NNBJBCInsAARCSiJ6aHALp+Vl5XkuGhpSObSljSvfOyleLAu7VpvL'
    b'LjVv+yYIBUbR9TAaAaRq4UiLlqjSDjTwlCBfeWB/xesxAwwBWE6JWDBJPDhJ3EgRNRKEjQmM'
    b'QIx8sUgmtT64BYC7+qGaiq7x2DhBeS6FtyNMy8RphNlevB8DJOACjn93AwCqbkHV2iWK9jGa'
    b'FGRXTXK5y7RvloDwza+A+inVMDADzJfLFQXMAtNAGhjny+R+kw6Ed3b3lA/tuwcfNp6a6w0O'
    b'AwQAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin35 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABT0lEQVR4nO2SP0tCYRSHH18v'
    b'lQapRX+sqMGhMoLa2qLB79Bn6AMURFO49CGioKWloSJaCyIJHArCtCFc0iAtTdOr933v23KR'
    b'TLOxpR8cDhzO7+EczoF//b1c3wuPkaiu54rUSxWMoB9Xn4eZ082WvhaAGT3R+eM4SkmUUk3h'
    b'HvExdbHVFmI0AOdJvF4PsgGwUVKhlET0eDqvUF7d17pSB63RpkS/V7GrNQckeSsUKBQL84tP'
    b'u7dtJxCBXhj24XKBNi3sYhXxUkKUTQxLkk3ds5w/aDEDCACZesY9HkBMDiAm+nGP+RGjfkTA'
    b'y0MiQXBlqfMKANbRjTYiYayzO7RZp7p3STGX56PLJny9PQgowAJqTm4GANjpvLbTOWqHcXTZ'
    b'JJLcIRa7CjlmBUjH/Aron6bqBmaBhUwmq4E5YBoIAUN8udxvMgDP2vqGdqBt/+ATaxKb5wlW'
    b'1g8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin36 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABKElEQVR4nO2PMUoDQRiFv39m'
    b'J8EkGKIBiyj2NiqItRC9g0fQM3gAD2BnEazEYwjaCkE0NtqIRkJiEJPJupvNjkWWlJPSxgc/'
    b'f/Pex3vwr7+XzDOcdSauG6eEk5SRjbE24mK3Ost5ASevsVtf0AwSRz9JGYYJIxthhxHECZf1'
    b'VQl8gI2iJiegHCROERlFYDQmp7Fxwt7Vk1M+wMGioqyFkhYKCvKBwgR6CjGarVoZLyB0kFNg'
    b'BIwCIzINZ5CxCN4J/cTRGztSwCGIOEygZg0C5fwNtgtKumPHvU3pfP8ggBYwRvP5FjIYlq69'
    b'AIDjlaBmGqd82Zi7hzY3t888NtsMXppHjXrx0Dsh0/J7+4Pzzco+EGcXZT8/N91qtRywA6wB'
    b'S0AVqAAFQH4BI2Vn5y1XvAcAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin37 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABMElEQVR4nO3RvUrDYBTG8X/y'
    b'njQ2omItCAF3J7tYcBEcvAAvwMVNBAdxc5F6Lw4OoqODg3cgOBQFP6v1A61o2zTpm8bXIaVj'
    b'Orr4wLOd84PDgf/8faxhAydvq6YV3aF7bYIwJAhDtsqPg71M4OB+wRS9ElH8QRDXCaIm7TAk'
    b'6IT8xMLO0pMlWYA/tkjO8rCNIjGarnRwRHAcIdAhm4di7CxgbnwDT00zogq4agJXRlOg31m/'
    b'TCagCRDbQ2wXZaUdAI6QEJF5Qrv3QDOuYUgwlgELRKWAiCBGDf/C6eua+YwuMTqPk7eIkxaR'
    b'7nBxdY2Xz50NBQC/Utmr+ytH1N5vaXx9I6Jo3Mj6/nb3OPOEfqbqzy/sls6XAZ026UKiAXfo'
    b'drVaNcA8MAMUgCIwCXiA9QvWcG7t4wVDvwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin38 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABKElEQVR4nO3RsUrDUBTG8f9N'
    b'Tpq0BaW2i4IuTiKIoPgCOvoAXd30CcSxjk7dfAkFVxftM4ik6OLSWBFaU625TWN7XULGZHTx'
    b'g8NdzvlxDhf+8/dRRQ367Nok3YBZGKG1RmvN+sNFNpcLjA7bprS9xuz9i1lvSDwaZ8jUNmw9'
    b'tpXkAe7+JojCUkCcIN8TRAQRYaoj7upNY+UBTnMPq7GAqlVhsYJd9RCxM2R5Z4NcQE0SVKWE'
    b'ch2UJyjPQcRJAQcmP+SeMH8bMe+HYAxKKbAtbJFsCyVS/AvR6ZVJ/IDYNpTLHvMwIhlH+M9P'
    b'uCW3UwgAK63WeXB0D4OXHh+fIZZl02V4fDK4vck9IU09eO2z1rk8AKZpxenrFk77ftcAu8Aq'
    b'sAQ0gBpQAdQvUkVn/iMYEbwAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin39 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHUlEQVR4nL2SP0vDUBTFfy9p'
    b'msTSWDHiqNDoJOrooIN+AXdx9kM5iq3g4OjqIjg7VBCEdtLSQbREk5g/zyUtYl9KiuCBy4PD'
    b'vefce9+F/8J560KqeK2sQMda6al4Ma1or/0gLQmGzLg+3lDmVn4Tu61Od3NtafXpeciXH0CW'
    b'oelGoclY4GyQyEEY0x9GdPs+gR+gJwmaEBhVs1BgvIPLux5vUcbAjwnDkCyKEGlKxbAw7Vqh'
    b'gHKu/fa9jP0A27SpOw3c+QVODxxlrvIXbo62xO3Jjvg0te2qVcOd0ws7KI3Dq0flHfwZU+8g'
    b'h5aH+PGOkE3cgcKgDiwCJpACSR4fwGuZDkYwgAbgAu/ACzDzXhxgedYiALymJ9eb3oTjN/ex'
    b'UX4OlJ+uAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin40 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABFklEQVR4nL2SvUoDQRSFv9kf'
    b'15VEFgxYCYEsFlZ5B9/Bxso2YJnahxCsYqcImlJ8AB/AWitDUsQYUIJO2P+x2QRhZ8MGwQOX'
    b'gcs951zuHPgvXF3fKF3fqCrwXrsf6PpiFanTR5FakJhcHIfaWatAuuP1oNluDibPSBmhEoEp'
    b'yn2WAo9vXTULhky/h4ymL8h5SBoZGAiszXKB5Q0ennp8RRM+5YggiIlDUJnAtAWOa5YKaKVP'
    b'bx01lzG2beHWTLy6x9nhWDur/YXzo1BcnmTCcqP2hmPgbe2VblAZnT7aHPwZK3OQw8hL/HoX'
    b'yAo50BjUgR3AAVIgyUsCH1U2WMAGPKABzIAxrH+XbWB3XRIAfstX+y2/4PgDSQJPCyyksPEA'
    b'AAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin41 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHUlEQVR4nL2SMUvDUBSFv/ea'
    b'0EYwtFQUHERoFFzEyX/g6iBY8Af4O/wX7k4FFx3cap1cnF0UBwtFRVtbQltMkybPJS1iX0KK'
    b'4IHLg8O95xzuu/BfqF83lI6XWQWi2l1Tx4u0oZtSVQUSRhL22+faXuM30SgdPq9tb613Hpu4'
    b'/hcBgEj2mQoMTy6V/9Jl0Hqn99Ri4Hv4IiISgoI0EwWmO7g/u8Jvu3ivn3jBCE+NCVEYIoeV'
    b'IqDNVl8+Uv3Aw5Q5LLOAXbTZfTjV9mp/Ye+jJg56F2IhlDuWNMivlhMTZMbtxrH2Dv6M1DuI'
    b'IeMSP94Jopk70BgsAmUgD4TAOK4h0M2SYAITKAJLgAu8AXPvxQZW5h0CwKk4arPizDh+A3z/'
    b'UUzvi/c+AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin42 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABLklEQVR4nK2SvUrEQBSFv+wm'
    b'y7KrEHBRSCGCnW9g4RMI2ljZW/km24paWgiW+gALNoKljWBhJ6Ik/kF+Nj+TScYmQjZZdYOe'
    b'ZuZeOOeee2bgP3F4dKyaclrl4i3RGg+dEOirhJNXqQ6ehNo6v5/JjV5txBm4aY61usjO6EHZ'
    b'jw5ad46r3bWp9lrVhpflvCcZUZwy9gKkSOhIyf7lixre+DVXNQFX5IRCEro+kR9gGF2sBZNB'
    b'z6BntH9fIUgzomBM5AeINGdgmpxuLn+bbk1ARDGxF+AmOtd7682eZePs7m//YNseNeXXQ6xA'
    b'BwZAB5i6Ti2DEvqABShgHkiBGAiBBMhqAlEYfl2XCrIERHHKgqQBbSAH1ISAY9sAK8AHcFsQ'
    b'fgy2LHDhODbAczF1JnwC/d12b8kQljYAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin43 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABLklEQVR4nK2Sy0rDQBSGv9hU'
    b'vKClJSh4QfEBfA4foA/Qtctu3Io7ly6sK/EFBDcu3Ij4Am58gSISEryV3DOTZNxESJtgU/Tf'
    b'zJyB7z9n/hn4T50PLtSszFyxcIQ5c9Mxg2Zm8Gj11d1rTx3dGrWm0ScPRObgizd2tjsc3ytl'
    b'miP0xZRBF23qBABh8o4bm4RRgO8KpMjIhM7pw766euqWpioZ+MImlA6+I/A8QaOpsdbZorW0'
    b'yYK+Ov0KYTIi8CWeJxGJpN1qc3Iw1GBYL4M4SvBdiZd+cdlDg49KsFKH1/ztH+y9nM3Kl0Oc'
    b'kA4YwDxUP2Mpg4KWgQ1AASuABCIgAGIgLRmEQfCzXc/hBBD5muSQBjSADFBjBrZlAewCn8Bz'
    b'DvwabNHgxrYtADPvWkvf+S13hu0RF44AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin44 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABMElEQVR4nK2SvUrDUBiGnyS1'
    b'UEvFUqFYRLyPOHkDbq7uXoCTvQcHfxavwCWzi3gDiqWDi6NoI9jQND8nyUmOS4TYBG3Qdznn'
    b'O/A+H9/7HfhPnV9cqroevVjIt1ntpo1ikXRb+CeWko7P+OaO3ecrrRYAQHkC+eGy3dvkkSP1'
    b'4tisZgZ7znUlTF98kFOPxHaIAsFM+IhUEuiKe/NYPR2eljIqAdL3GXIe4kY+bhyyoht0t/o0'
    b'Bz2Mduv3EVI3ZB4L3EiQyYTO2jrm6ExjtGQGoYzxkhDleuw7lsa02lip2+7B3/7Bw9Cs6y+H'
    b'uKAGsAE0gco1ljIoqA0MAAV0gAQQQABEQFoChEHwde3nZgnE+SlzkwYYQAaobwB7MgHYAabA'
    b'ODf8GGwRYNn2BOA177qUPgHPUHoGHv0N6gAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin45 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJklEQVR4nLWQz0oCURSHv/nD'
    b'iJNKTSmWCUW0Cdy17wV6gzaBPUjQrqA3iBbiPmgZ9Ao9gKmLEh1hkHScyWFmbhtdVJdxJPrB'
    b'XdzLPd/5zoH/SKvVEmn/qrLHRqP5d4uzh7dUFlKDy/ZUqHqcqpEUMBqO2azkqD9Pl1r8Apw+'
    b'voqe7bKR1QlnzuoGWujhCoWBPWGtmFkNcG8HwsybKJFPZ+hiGRrnT++JY3wD+F7A4d42hhoT'
    b'xSHtvkt2XbomOaDveOwXDKzdMnrk03OmjL0oPeDquKS4k0+qVo78loUeeTRPqkoiQZa7QSAu'
    b'XkaL2XWgMD/JBovUy4a6U8gAlIEKUARKgLmsuQJYwAFwBNSub27FvFiTFeg/7gL4AGZADqDb'
    b'7QD4gHSbX+O4XIQsCQwAAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin46 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJUlEQVR4nLWPvUrDUBiGn2ja'
    b'GK2pCRLagLX4AyJ08QIEwRvxBly66ODgquDkHRQHHcRNB0G8AndTLP7G0h8RiTG18bjUQT20'
    b'UfGFM5zDeZ/v+eA/4rquiPu3T/ZYKu383aK4b8SykBrsuYsiqSZiDZICas1nco7D2nG6p8U3'
    b'wOqhIbzGNWZqDELtFwatBOFbA69exR4d+Rng1CuK4SEdXhPc1F3Sep71o0zXNT4B/JeAidwM'
    b'qpIkilpc1s6xTCO+QfXhjqxRwHZ0lLbGffMKP/TjA5bmDpQnPyBrTmNaAyhtjZX5W6UrQZYT'
    b'b1lsn+U/dlcBo3NiR9ktLwggA4wDk8AUMNizCFidwixQ2NjcEoAN9MsK6pe7AB6BEEgBVCoX'
    b'AAEQyQDvLwpUjaJHKLYAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin47 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABI0lEQVR4nLWPvUrDUBiGn9Q0'
    b'0BhaDFEKaSpYf6Do4J0Izk66uDnq4A0oiHoLpZvg7AU49AKcIpZioWpIrZQmsVqOSx3UQ3pE'
    b'fOEM53De53s++I/4vi9U/2Zkj7Va/e8WV6UtJQupQbB5LvSsoTRICggHPbySS6O8M9HiB6Dh'
    b'bYuw3cFyHWJDyk8HJIZGphvTfXyiaDu/A/QPL4WVM0l06N7ekys7XK/spq7xBZDEEd5yBQyd'
    b'97cRod/CLsyoG/Q6AWbVw5u2GRoaz+0HRoNIHbBU39MGUURhwWU2l2eYzbB6c6qlEmTp71+I'
    b'1vrB5+46kB8f5WjBxpkAisA8UAEWAXNiEbDHhSqwdnR8IoA5YEpW0L/dBfACvAIWQLN5BxAD'
    b'IxngA3olU8I/PXQGAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin48 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJ0lEQVR4nL2SzUoCYRSGn6lp'
    b'xqyY0iTDsB8KW7QJqmXQyvuoFm36oe4juoPcdg+D6yhMKAiRyFyUUub045cjM/G1CAQrmBkX'
    b'vctzeF6eAwf+M9s7e/LnrCdIgfyFB0im0PoT920ggK3LencnbGSFbOhQvnnozmB1qo+79yb1'
    b'ao30Sb7DwrNgPSt2bV2hVLxHVT7pdUQwg/SsdlSyBFalgq4qRJKTHJTstoVngavDRbGKisvI'
    b'RAJjdJjXl6Z/g/KzoFa4wojHMcZi9Ic1nh7f2nvFqwBgLXMqx+emiUQHEI0Wx0tRX1xHNvOW'
    b'3L+1JaABQ8AgoKg+eT0c1jicCaWAJOACDvDhSZqmKYEQsAIsA4vAAjAPxLwM1LPzHEAKuAYS'
    b'fH+1AGzA+QLUflxSIY0dcAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin49 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJ0lEQVR4nL2Pv0rDcBSFvzT1'
    b'lzRYogYrUpGKljroIKjg6IO4OQna4qzv4ODgrqODD5AXUBFFQS1qkA6ltWqtbeOfCD+XUqgd'
    b'knTwwF3u5Zz7HfhPrW/k5N9dJEyA7LKH0NFN9/dQBB5V9i7SvVXYtk2p9L3iPJZ7I1iaWOXZ'
    b'zfNUeWfzMN5B4RuwZQ9kVdHgzimiIpDfIhzBcjq7U6rlqZSaiIjG6JjB/v1sm8I3QAiPS+cY'
    b'VWokkjqDVoxavR6coPj2QOH2C2tEx0oYGLpO+aXavit+AQBrBzGZmjQZMk0a7ge5+UIgX4d2'
    b'z1Oy1V0AcaAfUKIB/Zqhx1iZusoA48AP4AGur9O2bQnowCKwAMwBM8A0MOxHED05PQPIANdA'
    b'Emi25hPwfgFt+VhN/yDmSwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin50 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABLElEQVR4nL2PO0tCcRiHH2+d'
    b'i4onK6RSqSBsaHHI0amtD9BUUw0NXcYQWgua+g59hbacWiKjoaA2T3ZBbfCER84x0fy3hGAF'
    b'5+jQD97lfXl+PC/8Z7Z39sTPnXeQAvELHyD6/umfuGsDT73Jc+ZguBeukhsiWO9QqrwMZxBf'
    b'W6ZVrPJm1jiPr/dZOBZcJjZ3VbuL/lpCBHy0AgMazG6tnFjFMhXrHa8kMRMax8ge9SwcC9Su'
    b'l8fCHZ8BHwl1lDE1TKNhujcw9TL3dpVJRSMW1JBlBcOo9e4epwKAs9iqmI9OEYlo2E2Ludtj'
    b'V1xfntI5YWQPBTAChIEQ4PG75CVZkYle5FJAEugAbcB2JPP5vABkIAMsAWlgEVgAJpwM/IXr'
    b'G4AU8ABMA9b3fADtL70pWosibfjjAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin51 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABbElEQVR4nNWSvS9DURjGfz33'
    b'3F6txMDARoRFK6nFRGsSg0XEJMRgNhMlIvEHNP0XfCwkTGZiMohI3PhKb2l8k2grxU3bY1CJ'
    b'qy4Skyd5k/O8ed7n/ciBf4Wh4RH1OSe+K9h5LKiNe1uN79yqntUTFQ5HyjTSrbhjwYxc2Yp7'
    b'u4hPavi9kuX98zKd6wRbgy0bN3YRXQgMXeD3Cp7a+39vAJDLF5GawJAafl1DaB6mo1HHHVwN'
    b'+tb2VDZfRAhY2U51mefpGU0IkqnyNRyIXdhq7CinBtYPVOeiqXrnNx0dY7G4g0uAyJKpugO1'
    b'NFT7eBZQIT3oXh2ZPuY0aTkaJCwn93wk8URW1VQanOXBTFxzcXjEnWWxOzfq0P0FGmBMTkzM'
    b'lt7C7YiiNN17CMAA6oC6y5vbKaARqHf7SB6gCvABOm+30oA8kGluagbwA5abQQF4ANKAtxQS'
    b'yAEvobYQQBbI/Lj0V2gNBFWwJaAAXgE8RXTENNTeuwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin52 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABd0lEQVR4nNWSzyvDYRzHX3u+'
    b'P7bvmEh+lIMSElNcOcxfwUHkJknOa0juDsvBScRNKUlxUspFqdlpibbv/Jqo9d0YbabHwayG'
    b'L3Lzrk89z6f35/28P+8e+FcYGh6RH3vqdwPm/Y7M5CwOz5eJXB/QmvCxtrryO4GxdXxWLkoq'
    b'e42ulWFo5exFgp94wk5gsZ99K2eiCh2nYuDSPFT3hH8vAJDNp9AUDV01cGnlCCGYmZoqycFW'
    b'ILBVK5+ekwiHwm5oqe/sJjwrhMC8uCrhOT4O7lwOyZuHI+Ixi9tMAiNbw/zgXZEXDC7IycmJ'
    b'4l0FGN8Qsrd1gIaqNl5EEl11o+tp8uceTuLJkgeisZi9g+3oqKx015HMHXMSD2GeprkyH9mc'
    b'e/7k9K9QAGfA758rnIVdiKLg7r0E4ATqgfrE7d000AQ02n0kB1ABGIDGW1YKkAfSLc0tAG4g'
    b'ZifwAlhACtALpQKPQLaruwvgHkj/uPRX6OzwSm97hwR4BbQgdV2Fgkm/AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin53 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABcUlEQVR4nNWSSyhEURzGf3Pu'
    b'vTNdpJGUlOQxkkextZiRslciG4+VYmmhJo/E1mays5SdrGSnqVlRduRRmOs5Mh7zYLxnjoUh'
    b'Fxdl5at/ne/0/b///3wd+Ffo6OyWH+/Edw0Pi5vyem5FBlsm5FJBt3S7PZ80qlWz39nqSe6f'
    b'kTyJougOtCwdY2r+k85yg8bobODx4AKhqW8GTTva7w0AUvFbFE1B1e2omTrCJhgZGjLlYGkQ'
    b'cPXIp0gCFIWN6YWG07XtUSEEe4fH382EeO+0DNePy+WKPunPaZPzpV2miT7fpImrAP7cdlnc'
    b'7MFZXogtdoeS4cAeUzH0FMHzPdOAoGGYuO09CffPSD3PSWo9xNHqFluXIXYTYQYifpPuL1AA'
    b'x6DXO5Y+C6sQRXq71xKAA8gH8k/CZ8NACVBk9ZFsQDagAxovWSnAExB3lbkAMgDDyiAJRIEY'
    b'YE+XCtwA97V1tQBXQPzHR3+FmqpqWV1ZJQGeAc5sccjgfu8PAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin54 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYElEQVR4nK2Tu0oDQRSGv9md'
    b'zUVUCPHWeME+WlpoK75AwMJCsQ5RfAF9AQsFCxsLQYOi9loE7BQ7O1GrFAYJZOMt7s7ujs0q'
    b'xvWSgKcZ/sOZ7/xnLvDfMTs3r1upN74mervTLTWMAO6Hx9m8snWxqvRFTend29qvjuRnkcvl'
    b'l8v9I9y5AUkliPkeB9d28w6y2ezKk69RQmAIjaN8Hl/c5gE7hQLSMknGTEzg2Q14fVXNA9oS'
    b'ceIxk5OL0uL2WYkHxyNw6kztX/54DuI3+sTqofbMJKmBITrTKZTrcTTZ37AncgvvMbVzru2K'
    b'jSElpmUhBPT1dLBVdvVeRekIoFg8bbB5PDMmDFNiSAtDSoQQtEnBVvFmZbrLijrPLyx9N6f5'
    b'16gf78Bzna/5PiABKCAI1yrQUPgdOQW0Ay7ghxrAA+ohwA11wx0ngEEg/ilnhDoBWOFI0aZr'
    b'6xt6NJNp6Re+xxuy6nLf8G9A/QAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin55 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYUlEQVR4nK2TO0sDQRDHf3u7'
    b'lzvi26hJ46uwFFvrfIY0Voq1xHCthfcBxBf4ESSFCiLY+mhEG0FLwcLGQjBBjVzu4Z3NRYzn'
    b'IwGnWWaY+c38d3bhv212bj5qJ1/7GsgOZtpqqBLEiQsOb6xobGAKU2a4q1yRH18SLQEWForL'
    b'qZFdql4vXZ5EC3s4uV37dYImCYVCwa6HVUIcNKHjBQ6vTq11wHa5jJIKM9WBQOH4zziu2zog'
    b'bRoYeorj6/3SweUKNfeRwBVYe50/bubHywGYXeuKQr1Obtigrz+N5wfY+UpTTWKNDSuVe6LH'
    b'ygtSgdQ1hIBcJsvxvRWdP9hRAnB0dNo05vrMk5BKIJVAKYEQAkN2s3O2ak8P2cnJi4vWdzrl'
    b'X1I/3kHguV/jOcAEfCCMzyrQlPgduQ/oBDzgLfYBAsCJAV7s+58LTWAUMD7FtNg3AT2WlGy6'
    b'sbkVTU1OtvULG/YOe2lnJYhXyfsAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin56 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABaUlEQVR4nK2TO0sDURCFv3t3'
    b'N9kYIwQfCYgoFlY+focW2qQUFesQRQubgGktfaGFpRILsRFMFcUfYCNimUa0EVGJ5rG7ybXZ'
    b'iGsSTcBphjnMnJkzcy/8t80vLKp28uVPINLb3VZD/ScwflPiIZlW4dFhRDjI222O6Oq0aIkg'
    b'Hk+sj2QdnJ4nqloAJ+TjcT/z6wQeCbFYLKVeC8iig9A1KkWLYv69dYKjdBpN1zGCJkqX2PkC'
    b'ZavcOkGH6cfw+7g7u1y+2z7BeslTokK2f67pZZouB+AgOqN8dpWhQDc9wS5s22Yit+epqTtj'
    b'zc4HZtXz+ys6Ep+QCAThSB9vyVP1sZFRdQQXF1eeMafuD4UuJIaQGFJDCIEWMrneOU4F1ybr'
    b'J08srTTSqf0l9esdON5t60AUMAEbqLr+BfAkNmIOA52ABVTcGMABii6B5cb290ITGAT83zDp'
    b'xiZguJLqm25u7aqJsbG2fmHNPgHYc2pvdREWXwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin57 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA90lEQVR4nN2SMU7DQBBF36xN'
    b'gCIChCyQaSlSIApqJCg4GB0RFZegySk4ARVCoqBKA0FIZh08bOJ4aewoFPFG0PGrGenPmz+r'
    b'hT9KAE5vH8+WGdKD7bvBeSqtAIDL+zdfbazhOx2i9YiJmzF8ydjd3+HmcHMpwMwBJ4moGCQ2'
    b'VF54L6YU1gZPMIvNw9OIwguZTtFPRW0eBMRNcTF43uodpYgRnCspPiyahwHzBL3jvcxEBudK'
    b'vtShNseNx0FAUFf9a79Sgt/qHwDisAWABPBACUwArftWgADduu4CFeCAvBmG9hM80PzlYb31'
    b'FZgtmlZ9gwQY1Sl+6BuyxVH/BJ92BwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin58 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA8klEQVR4nN2QPU4CQRiGn9lh'
    b'7QjVEgsLK2JBQWcHR+AG2Jl4Bg+g4RiWdN7AI9hgSWK04CfhZ5d1mNmBsRkSLFgm2vlW75e8'
    b'3/P9wB8lAO4GdI4FLs6Tl/v2TJQCAJ5eu06eKWSsiWMwxvI5e6ee1LhpDI8Cor3ptZ5FwQIR'
    b'bXFYFmrMOtUnT4gOi+HojYKUdDNHKU2e2XDA7YBas3FJJATaGLKVJl8X4YDr5tVSSok2BrUx'
    b'5JnlKwBwUg+PfRe0wW/1DwCVwFwCOMACBlC+LgUIoOp9FdgBGsj2zVB+ggNS7z/81AmwPQyF'
    b'/iABpn6LH/oGXM9TuhP9qtsAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin59 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA80lEQVR4nN2QzUoCYRSGnzMj'
    b'1EY00mwbIgTWNXQVrrqJ9l1A4UroGrqKIFp4DSJCCxGChMKZIWe+Mzmfm0+whTNT7XxX74H3'
    b'POcH/ikBeK73rnYFWienL93Jg+QCAF6vB/bQWA4UKuKTpsrH7I1G7ZjG8HYnwNuY9uONSGDw'
    b'MmCVkcwXBMmy8ARvu5iOxkhk0M+Q2CSE+gvA01Gv1jnrICKoKoH5ItK4PODy/GLh+z6qSqyG'
    b'0CyJ0qQQUKi7+74ttcFftQeASslcE7DAN6BA7OpcgABV56tABhgg2jRD/gkWCJ2fuanvwGo7'
    b'VPYHTWDutvihNfToVMFZUtCNAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin60 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA2ElEQVR4nN2SS07DMBBAn53E'
    b'SUxTGkBCqgpXqLhBT1HO0WPwOVTYoB6iS4iouummSUTqho1bAVIbR+yYzciaeW8sj+GPIdoa'
    b'7l/y5v1tPTlW99sEw1FK9bHKemnKeT/kqh9ykUQ0nmQ2VKJVAFD6IWeBx0Z6COFTGMnzjRIA'
    b'0kWgE42MAmKt0Foxf12s9zUnQRyrA2zMjvHd7aCbwMJSCOraUJU10yxvXFgeHp9ONjrd4J8L'
    b'nD7StxDAwOYt8NlF4APXFjb2XLgKQjs5B36s1fUNLoHlbxjgC/dOLCyOdcZfAAAAAElFTkSu'
    b'QmCC')

#----------------------------------------------------------------------
pin61 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA4ElEQVR4nN2SP07DUAyHvxee'
    b'kveSSElEkzKA2Bg6cgJmrsB5OpTepKeoIlaG3KFCQIRUGGjIXwZSCZAgL2LDi2XZv8+Wbfij'
    b'iaGCeRp3m/v84qe8HAIcHyU85wfrIHII/JDITwi9GGHVXJ6sxCAAoJEvWDKi5IkdBTSPXJ1m'
    b'AsAyAfi+g7RbXK1wleLmNtvuc0YA7di4SuFpTdO2nM/OwlEAV3+IhRBUVUXxVjJPJ52JlsX1'
    b'8tdCown+OcDokT6ZAMLe10A5BiCBaS9u+vjVFOD0ne+AL2c13cEh8PBdDPAOO8Qv4KgK7yQA'
    b'AAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin62 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA1klEQVR4nN2STw7BUBCHv1dN'
    b'+16l0iDqArpwCldxAGtnwBncxQUsLFxBWgkhEtE/WptKkNAndmYzmcz8vpnMDPxooqpgHYyK'
    b'aBsO3uXNKoDf6RJyXrSUi+O51NtNnLZHLYPGfCgqAQDWKcW0wNhfqMVHxC6hsRgLAEMH4EoH'
    b'KzdQUiKlYrlaHu45LYBt20ipUEqR5zn9oO99BbiLhTBI05Q4iVn3RoWOlsl09rFQa4I/B2g9'
    b'0oMJwCt9BiTfAEzAL8XXMj7rAuyy8wZ4OqvuDlpA9CoGuAEIyi/QeulybgAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
pin63 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYklEQVR4nMWRvUtCURjGf9dM'
    b'TNPBCCLKsMIIHKolgtSlLWhuCKKGxtr7B9ob28Klhpaamh2Clj7WjEIj/Lj5ce/V6/XrNKSi'
    b'qaAQ9Ezv8573ec5z3gP/DWmQ4cu4IZKKzvNLjGjkjdujLalp4Pf7d8Ph8HmD79xEHvbX3UsJ'
    b'VeezYFCz2rAhUdWLHC6ONXVtCQ6u74THO4/DbsdlHcZpNpHQCsSUPCkDnNQ4WZls05hbyZrP'
    b'x1M6R06yoCExYTFRrFQpGWX0TJ6y6HyxqZXszTqk+1AIOasiZzUSGY2KblAp6JRUlbONhQ6H'
    b'jsbFR15cPb5iG7HisgwxboHj1bmeyzb9bmxP2SUto5BOpUnKWeKy0kvb3QDAbXOSk9NEY0lO'
    b'N5cH+uq/QzAYFP3M9RvPDIj6fK2lFl130EAgEGikmAG8gKdeTwOjgGTuoQVACPEOWPlZtgJ8'
    b'AeX6cbWv7PUUPS/6Bmv6e+dBs49KAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin64 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABY0lEQVR4nMWRsUsCYRjGf3eI'
    b'XWhFSyQUZlDRFkU4qUu1NrQGNdfa0NAiRP0HES0RLY2NQjUdrdWWRGJIKZ13pp5wcppfQyra'
    b'JSgEPdP7vN/zft/zPS/8N6RexLeZqDDMNx6f70gk05xsp6XmBaFQaENV1bMGj8Zm7teCu3O6'
    b'meKjlEBWLNzSMHZZZnX2uDnX5uDwclFMTfvxeAYZUEbxukfImkm0/BOmnUKRfWzOX7fNuFrJ'
    b'wtwySe0KCxe20KnWJqlULSp2FTP/SQnd8S25laxMHEixizS5QpZcUcPIv2FbYFsSVkliZ+nB'
    b'kZmjob7ui5uHI/oVDwN9PgbdftaD5x3Dln82QmN7UqFQRjfyaDkNzch0mnVm0MBQf4DX9zi6'
    b'sDjdive06r9DJBIR3ei6tecCRF1fa6mFI8RWhMPhhgs/MA0E6vU44AWkX0NsQAjxAih8b6sI'
    b'GEClfvzZlfe6i44PfQHZv337aiaA0gAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin65 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABaklEQVR4nMWSO0sDQRSFvw0b'
    b'NBokSlAsYkyhNiIWYiEkwcbGxh+g6A+wESQg/gALxcbGxsLOzkorKwMiWKiFgk8SfMVsNprN'
    b'k81jLMzKxjUQQfBU917OmTlz7sB/Q/oNWVvdF5lnhfuzS+4eo8ze7EhfB/j9/tlwOLxt9Mej'
    b'C6dDyzPD2UiM/G0MR7YMLgcFSnjW5750NQ4OxkNioNdHq6uNpu52ZLeTTCRO+vqJ8oNKpdNJ'
    b'326oRiObm6GJMd4OzpFjaSQ1S8XrppQpoOs6WjEHatHyLJu56VyakrYjR6SUJFpMJfX0SoEi'
    b'eUpo6IwcrlgyswySa3viYmuPlhYH9i4Xtp52Bjfn64Zt+z7oWJyUUvk0yrtKQomTfInX01oz'
    b'MGD3uklcRRG5FNMnG79a9d8hGAyKRniN2pMBUeVXTLWwhGhGIBAwXHiBfsBXrT2AE5B+DNGA'
    b'ECICNPO5LQ1QAeM3lRvyXnVR96IPlNF+sX2i+K4AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin66 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB10lEQVR4nKWSP2hTQRzHP3fv'
    b'3Uvy8kL+NZagEtAqaIbQsbh1cNDdxUFQyOrUyd2hGVzrEHFwqziIIDi4qqOFaIQ2dTCRgLbP'
    b'JC956cvLOQSLNX86+JuOu9/vw/dzd/CfJeYdNJttvS8zPN8LuJY3WOnssrpanOqX/26Uy+Vk'
    b'ywv1ZiPBy68BjhLUD8e84QJPPvv6VEC73XYf7QxxLIGjBI6CuJqsQy3Y2np8AjIV6cGHgbYk'
    b'WAZEDIGSGqlHmFITMSS2Kbl1yRYzAfV6Xb/oF4hIgWXAu2afnt9nEPgE4QiBQJkm518/pFqt'
    b'iimFSqXy1FGCTwch71t93H4Xd9BBxSSpjE0yHUMqjodnKtx762mAHz2Xg94vslmHZNomFlNo'
    b'DZ435NnameO5qUu8zQ5HowA/GBKPR0ikYmSycXIpm6W0zYb9c/ErrK+vibuqThiOMZVBxDKJ'
    b'KoOzUcmdwTdKpSsnUs/9SAA3XjX0cj5JbinBZsGa2WsuAviDAK87RO9+/JNWABoYz1X4uzac'
    b'Fu6hx/3LywDngByQBhJA9DQDisXixevbexooAVeBFaAA5IEsEF2YoFarNdLDDoADxJkoHwE9'
    b'wAX8hQBA3xzvw8S7AXwBvgNdIAT4DWGkm2np44EXAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin67 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB4klEQVR4nKWSMWgTURzGf3eX'
    b'u+RdGi+5awoVQayCtBlCnHRspCAKDl0EHRQC2ewgDl3EpZODo9YhCCK4Cl0i0cVd6GAgRelk'
    b'W6KDwVyTu+bunkOqJL2mDn7wlve+7/t/33sP/hPKpIOdnbb8rjR49/UxpdN3mOneolQqxPix'
    b'jWq1aq09fdCpfbqOoQn0hImumuiawBZzLC88G9OoRw3a7Xbn1eYypmEjDAdTtw+XQyQHrK+/'
    b'kKP8xFGD8uo3dM1G1w4nqwJNEeiqQFdNzl3dnVyh1WrJj+59DG0o/Ly3gT8ICIKAKIoA0DQN'
    b'd+MutVpNiRlUKpWXiyvuva0fdYIwpO/5DIKAjGmSNHSkBM/3eXKjrxybAODRe0sC9DyPvucz'
    b'nc2Ss6YQyRQSyX6vz8PLu391sUtcVOuEYUQQhKSFwMqkcbJZbGsG+1SeJfFhjB8zKJevKEtG'
    b'g0hKjESCpKGT1E1y5jylgzcUi/NjqSd+JIDVelrO5h3yOZvbc5vHcmPPOIq+5+Pu9+h8cf6k'
    b'VQAJRBMrjOJassHPX11uXnwNcAbIAzkgA6T+1YBCoXB+5a0mgSKwAFwAzgKzgAOkTkzQbDa3'
    b'VXcaYApIM6x8ALhAB/BONADkpeg5DHtvA1vAHtAFQoDf08GR8strQYQAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin68 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB4UlEQVR4nLWRPWhTURiGn3t7'
    b'cnKT3KS5+VFsxQoVQYNEcdG1o4s6ODgIamqcHbTgIOLgIBQLLnUIFgIOIrgKgji4iGhxiKZL'
    b'B6GUINL0L8m96b2fQ1Ty1zr5TofD+73neb8D/0srKzX58eK9fD51S74/fCmLixUZ5jP6L4rF'
    b'4ujc7fv1b5ceMRIJY0Y0ZlRjWprwxD4mZ6/1zJj9AbVarb50ZQ7l2KhUDJWyUUkblYojOz7z'
    b'8097SFR/wIP1E5iOZuT3q2ZEY1ihzjmqOVcP716hWq2Kf/dVB93S/Hz9iXa7TeD7iASdAcOk'
    b'fCFKqVQyBgIKhcKzGU5eXXvzhcD38TyPwN8hFomhQxpBcF2XM6sLxlACgA+HpgXAc13anosz'
    b'6pCIJwhbFojQaDY5Wpn9OzewxO2FAkEQEPg+USuKbdskkw6JsSzx/Rmaz6d7/AMBU1NnjVa5'
    b'iIiglEKHwqiYhT59mNrj8+Tzx3qoByp06+P4dclksjjpNMm3d4Z6B76xW023RaPR4Gu8+YfW'
    b'AAQIdq3Qre3yDTY21hl7chPgIJAFHCAOWP9qQC6Xm3yXvixAHjgOHAEmgANAGrD2JKhUKstr'
    b'jgKwgRidyh6wBdSB1p4BgGzeuwid3svAErAKbAI+wC8NR5nZkc6pxAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin69 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJElEQVR4nNXSv0rEMBzA8W+a'
    b'llZOMnjnn0EQRBDuAXwDFzfB6fZbfA03X8HJ1UFwdL4XcNDNwcFZ7g6apm2aONih2lq7+oMM'
    b'gfDJd/jBvx/RvMyfln40ikliyaYUqDBAhYLceVbWs7YeU3l0mpOmObcnExE2AeccV3sWsP3f'
    b'juHyxQHwDbDWobNsULotO4Ait2idDwLKMuwACks2sKAoNtqAMSVaDwNy01FgspJU60GAMUkb'
    b'sGVFNhCQYrsNJFHM9fIA66qvR1KAEODBeY+rHDKQRFKSRBHwY5F+mRjg9O7VBEEAwOPFYQj4'
    b'vwABjIH47P7tPZIhH+maxWy6C7ga0EEPsA/sAOpoS/H8cHO+mE2PAVUfgKyvQDZKFDABlsAK'
    b'qKj3/RPEzXAw8qeA4gAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin70 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABGUlEQVR4nNXSQUoDMRSA4T+Z'
    b'2GkVhoJaobhxVS/gGdwq9h4Wb+LCgqcQEQ/RnStP0JW4UOgkk0wmcdPCDNOW2fogi7f58kMC'
    b'/35EfXn6uIhHgwH93iGpGjLojegfnOJDjnZf2PIb51fkxrAyhoerpVB1oAqBu/Fi+1Vpc33+'
    b'nADQAHxVoY3plO591QacK9G6G1CWvg1Y5zEdC+w2oHC2c4F1bgtQWHKtOwHG2jbgvMd0BDbv'
    b'3wBUkvCeXxNiAASJlAghiERiiFQhIIVASolSCRCaH2nHpAD3L6rYYI83XgGxXrKr8hhIZ69q'
    b'mUiFsQXzKWdAWANa7gHOgRGQjYeXLN6K2/mUCZCtD4DZV5DUSjLgBPgBfoEK8AB/Weh1G104'
    b'm20AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin71 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABH0lEQVR4nNXSsUoDQRDG8f/s'
    b'HsZTcihGBUknaG9lKXkD27yEvZW9z2BrEbC31GcQfAAVbMQYxd3c7e2ezRpOL8RrXRiWmeI3'
    b'XzHw75/Um4eD0ypNV1haTVGbXZL+OnpnjfAxxT++4p8n+InBWou1ht27c0nqQAiB5euTWV/G'
    b'qm9LgC7weXgGsZ897z3G2lbRvfdNwDmHMe0AV7omULiC0DKBc/OAPKdomaAs8iZg85xgTCug'
    b'mgc47yhaAp34/wC00nSGF1QhICIoUYgIVBAIhDgXUYjSwK9DWrTspjecfg+OXi4ToPoLEGAD'
    b'6Nz2hk+iNWWRMxiPtoEQAaMWAH1gC8i6e32u3u+PB+PRPpDFArCLEuhakgzoAW/ABPDEK/8C'
    b'lEtzVX5hsUAAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin72 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB4UlEQVR4nL2STWsTURSGnxvT'
    b'JtMmY6shEmoSImhRFwXRjRsFF1kKAStCFOlP6MYfIKKrLqwgLtSFaDaiIIgIYpCIgpAiRFCI'
    b'iR8R0o6JmjYzzdfMcWEJjRNd9sDZXN73Pc+958JW1OtFZEsGDa17tZ48+mHLpWRkKIXnf+Zq'
    b'tSr1rtARIZlODNWof5nb7bbU63W+axPs8/+RaZrm0g8luPimKC9MDw87QZ5V1xARHvxUXE5G'
    b'XdcYCLAsSyzLEun0KBgNprQRGp8+cmtFaHVt9OvvXcMGAkQEpRSh3TFmvr3F4wiz8e3M7VI4'
    b'tsNcZBsLs+O3hwbM56sCcOVzh/QOm3K5zP2vTWKxGNlsltMhodfrsXPSd35zgAK4WlqTfG0d'
    b'01hmZk+MSrNL5UOBYHQvN49MkM5WcGybuyfi6LquXASFeovF/X7OdIqUf7VYOKgxHp3GeJdH'
    b'RNDGgqyvrvbN186NuP9Es9mUk4+LksvlxDRNST39Io1GQwzDcImX7hztn/XfIBAIqEhgjFKp'
    b'xKnnK3gdB6UU4XBYbdJ6gdFDZ18FAA3wDmwh5POQSqVYXnpJzeyi63oCiAPTG50ApoDJC8fD'
    b'FuD/m85nWZZkMpknQBo4BhwGDgBhYHSDwnNjXhfA+xvuLsZAccBGewAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin73 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB50lEQVR4nL2SPWhTYRSGny+k'
    b'TWKTizXh1qKmjYMSBwV1sBYxuAScJEOnKkWdFVzEIij+oBAQ8QfRRbRDRgeHggjRBH9AjYha'
    b'Qc21UmxI4pUGk6uX3OS4lNCY6NgDZ/l43/c833c+WI56dhVZlkFd60nxhOTMpJyPD3alcP3P'
    b'XCgUpOrM4TR/ER+PdNWof5lt2xbTNLF9M6z2jgLg8/k69F0Jpp6PycfqHd78PsXr+buICC9+'
    b'nONCfF3HNdoCLMsSy7KkUVd8LmUIrthA8YvDo+IRbKfG5ht7O4a1BYgISikG1q4k8G0CpIdd'
    b'w5PEBq7QbMCewctcGuu73TXg1ssRAbg3u4/RYBLDMMjOJQmHw6TTaUZCZ3Ach2C/Z2JpgAK4'
    b'nz8kn74/YKFcJ7p+B+XaDMYHk1DYxdFtBhcfD9NoNpmMfUXTNNVBYJgZDkffs8W+znzlLQej'
    b'OYJhmH1nIyL4+rzUftZb5msHejr/RLValZPTqySbzUqtVpPTD4NSqVSkVCp1iHNTO1tnrTfw'
    b'+/0qFBgin89zNqODeFBKoeu6WqJ1A71b9z/1Az7A3baFgCdMIpEg/8pmwSqjaVoEGAI2LnYE'
    b'WAP0H4/pFuD9m85jWZakUqlpYBzYDWwHNgE60LtI4bp5TBPA/QeQKL/grVo9mgAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
pin74 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB6klEQVR4nL2SPWiTURSGn5uf'
    b'JiHx0ygmlWpsrCiooIg6uOgiAQWHVJxqKYhDBxG7KB10sDWDUIV26STiEDq4uChIzRCNIv5R'
    b'awnYZLDQkJDUpia3TZN+x6WExkTHHjjL5X3f89x7LmxGvRtFNmVQyyrfey7LY5MyHNrVksLy'
    b'P3MmkxFzfhFWqoR6gi016l/mSqUihUIB40cR66lOAFwuV5O+JcF03yNZm/iI/cEkhYk3iAir'
    b'I6+IhPY0XaMhQGstWmupKWEhMYOjq53ZygLlwWdU9TJXj0SahjUEiAhKKTq27yR5KYhpV/hv'
    b'XsB9vxtThC1D3Yxcdj9uGTAbGhKAX73jOO5eJJ1Okx99SSAQIBaL4bx9nlqtxg6vo29jgALI'
    b'3ngiS6+/ka2W6Dx5mJVkhun8T/bZtxH8FGHq6ABrpsmxqYcYhqGaCH4nkvjf3iE7fI7SzBzt'
    b'sUG6rFv5WppHRPA4XSyt6rp5rNfe/CdKpZJ8CF6TeDwu5XJZvuzvl2KxKLlcrkn8+enp+ln9'
    b'DTwej3IH/KRSKb4fuI5pt6CUwufzqQ1aG9B2/ErCA7gAW8MWrLu9hMNh3us5dH4RwzCCwF7g'
    b'4HoHgQ7Ae+usTwPOv+kcWmuJRqMvgB7gDHACOAT4gLZ1Csv4gCGA7Q9z8L8OPeXo5wAAAABJ'
    b'RU5ErkJggg==')

#----------------------------------------------------------------------
pin75 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABzUlEQVR4nLWRPWgTcRjGf7kc'
    b'CYYkNE1sj1Ti4KKTguigFBeXQFwcHFxEUTo5iEPdOgnq6sciFEHsaAdBwQyCwQ9URKXFDzCJ'
    b'UlPolRD+d9zZ+/i/LhKQXO3Ud3x5+L3P87ywXfP0Ose2Db7lvLhVk8X1UOZ7G7KV1khaHjj7'
    b'GS/U9IOYwWAw9z9AKmnp+74AaK0BME2TbDabqB1xMH+uLA/WNFprbrz7wSsHFu2Iq287iXFG'
    b'APaVDl6oub0S49urOHGKb50VDCON7/uilJJNAQuXkYu7TCItzFjChf01gkhzyG2TyRWHcTYF'
    b'fP9QI45jzlvQarWwLIv2wKPX6xEGAXPL7kiEkWIcx5HTT76SLU9w73CJU4+/kDPTFCoWU3mT'
    b'1x+XyU/toZozuTNdTQ0dLD2sC0ChUEhFwQY7jDRaBPfXT6J8hZsHi3yyfS5Netw/UmLVDf69'
    b'fK1RGWm52+2KUkqUUuK6rjSbTak/aovjOENt4m+BLFABxpRSSzMv+/R/R5zx3vBs4ih3j++e'
    b'BHzAMQAWZkvyt9BxYC+wE7CBTrFYnF73QtbeP6fRaDCeMQCqQBkoATB7Ii3APmAswVUaqCul'
    b'xPM8AU4CNSADpP4AGojGU3juBH8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin76 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB0klEQVR4nLWRP2gTYRjGf5dL'
    b'PSFeTJuUhlqCIIji4B8EcRBFXSLp4uaiqJNbRUq6KTjYOom4OCgOWh3EtWrAJe2gUakS6mJI'
    b'QBIhTSX9viOXer17XSQgudqp7/jy8Huf53lhq+btDCe3DL7pLDzISKl5R97VJ2QzbSRseejy'
    b'N7rrGr32k3a7ffN/ACNs6bquAARBAEA0GsWyrFBtn4PHV5Iy35wiCAJelC7xXb/k/fJdnpYu'
    b'hMbpA+ycOkPXc3hdv8pqS+j4LSrVJYyIieu6opSSDQGzN5Ds2BP8wOfsyEPGD07j+WuknYts'
    b'j5m9OBsCKosZfN/ndPo+xWKRdDpNY7VMo9HA++3zbCnbF6GvGK213H6zGztpcP1olVtzGayB'
    b'HSRSFqnYXj5+nSc5FmEotoeJ45+MnoPyq6wA2LZteJ7PgBkjEGGlsY5pa64dXqSyssC54edM'
    b'HvvBL6f27+XpXKqv5VqtJkopUUqJ4zhSKBQkPxcTrXVPG/pbwAJSQEIpVb734QCq2+KIekR9'
    b'dIbJU19GABfQEYDZ/KD8LXQI2AcMA8tANR6Pn2i7TaqfPXK5HLa1C2AUSAKDAOTHTQH2A4kQ'
    b'VyaQVUpJp9MR4DyQAbYBxh89kcM46EtncAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin77 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB2UlEQVR4nLWQP2gTYRjGf5d/'
    b'pwkXG6tptBBjaaGK/2ZBnCtxUUpB6FDBRUUEhzoIGYpaoYu0ICi42dFBncwgEpWqIIWIUVQM'
    b'oQbrKcbvrrkYc/e6tEclKejQZ/p4efh9z/PAeunhNQ6vG3y1tE7HpzNp2e/ewvuqiF8e7uhZ'
    b'UaDT8cBYCddu0Fz8Sa1Wy/13AsdxBMDzPABCoRC6rnf0tiW4fbJb6hP38DyPt6dv0Lw/jz2T'
    b'582pafknwBHtCi3bQZ2/w6K7hHy3qZTeEwwEcBxHlFKyJmD2AhKfHsVzXaJTIwzkTuA1W3w5'
    b'PkgspPt11gR8nE/jui6xq8MUCgVSqRRWqUK1WqXptvg8cr2tQtswlmXJ833nSIai9L2a5Nne'
    b's4RjG0luMND7UxSfvCQT3oS+M8nuRxOan+D13SEBMAxD++22CEZ1PBEWftXoWhJ2PM6h5t4R'
    b'uTlKf3GKRsX8++fJ7Ja2lcvlsiilRCkltm1LPp+XF71jYlmW7/UTXHzwbXUdHejNZDJ7AD4c'
    b'vERx4AymaRLp68EwjB7A8AGz4wlZfm8GBoGtgAl8isfjhxzzB3ONBbLZLOFtCYDtQDeQAGD8'
    b'aFCAXUBXh2GDwJBSSur1ugDHgDQQAbQ//Bu9ilYMQv8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin78 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABpklEQVR4nK3Tz0vUQRzG8dfs'
    b'fndXV80fYWAdIhJMDInOHTxpnoIs6CAEUeClQ8eu0sV7SARRdCsyunUU6x8wSCsoqASDfuim'
    b'q9u6sdPBzbJMPfSBOQzM83yez3tm+N8V77XHeKcx7vZ82BA+uxR9maXwjlKJUlG4WA7biSEF'
    b'8e21GOOqWF0iyZJJc/LRrhIk6+2X11eSJbNG96jZscFdGawnKL/ACvtOKEy/8vrGiLovxHG3'
    b'dzL4xWDhQYy3hr2fz1korooqentJKnnyFWGksiWP1IZT25kQLtzV3H9Urr1BFMzNoYhcRhw3'
    b'ua0B+DytueeYfEeLdDaxuIiuRtKJ5aK+rQySTbtcIjT0ae6cdvBIk1AuUV4183RJW9vWDDYS'
    b'VN+cjVFJ/HBfSyuShMPnvXwyb22N/aN+Z5BBHqlNYKozQ1E6T7VemLqpUKBQ4NCYgL0YwB58'
    b'r9H5uolBqmcihHS3UN9Fx3GtV4Vzk6fgAC6js2ZQh3o07PhUH048jqeHBvO4gmyt+zes4PlO'
    b'ejDQPxxrCZrQ+HN+/ryFf9THT7kpXMdfv/QH/8qD07PHlb8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin79 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABSklEQVR4nO3PsUvUcRzG8df3'
    b'd/7OUysC4Wg4BAmMgqKItiDCClxbxcmxpT9Ag4bmiGhqaWoUGtyMCKrligiiBu2G0oQD9Ren'
    b'3Nl1v6+DJBldHrT2DB8+Dx8+D++H//pnhZ9L/vx8DJ0h1hfZ2qTWKITb8oMCEsg/3YyGz4p5'
    b'RtpPsSgr6fRCkOzODjEjLTI27e2zNUfrvVVIIMzfPxcqk0IjtfrwljwjKxMfHXp5UED41cSN'
    b'ufj1yYx6dUmSf3fm2CCVXJhuhW4ByT5Xf6N8YUxp+LB2G6eOUKB5V+wW0LfP9ScKrdSJ8VGh'
    b'Waa56X215fQDvRHE1jvydYp94sh1tVdfbG/vnVMcx2VU/kgQXleZuMeHOe2FOy49Pml55eMA'
    b'ZvEDW/iGISyjOxo8XXgRx69cLOMGIppo4DPm//a7p2tXJyOmMIDB32vvAHj6ZYmZrPTJAAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
pin80 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABCElEQVR4nLWQMU4CQRSGv9lE'
    b'YMJmTSwIJXaCiR0FNYfwEjY0EiglXMDEO2DlFTyBQiOyQVHYEIJk3WwIxGxgLKTBXZaVyJ9M'
    b'MW/e+9/3D+xD/YGlovZqQcXbRsP5N5qdZJ+ivHopUozACJ0xeFY30jKfwZ0hVNcReGaT5U1t'
    b'K4XPQCxB0+ChabGwR38jeDmjlz5SJOPw7sD8tcMwGwulWDPwFmR0CbqE+AG07h9JX1SjE0zn'
    b'P8OGVOgSzDebr37vOMxA/C48ZVEAo0/4cAXnM+Xr2UgAkGsjkgkwJJiVq7BZGfbIc46gzzsE'
    b'8sAJkIKACBuUAorAFHBXZwIMtw1eX5YrCiis7r6F33QTTZmQSCm1AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin81 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABhUlEQVR4nM2Svy9DURTHP61S'
    b'v/M0LUVUGEhEItUQYw0WiV1iMF5GJhv+AJPBYGteIjFJLEYJQVKWvkaQkFZav9KiT+KJX9fQ'
    b'10bbPGHzTW7uud+c77nnfHPg30EIIf+SbysmNE2TkUQ1yfQLyWc7px8KW9PNJXk52IsJVVU5'
    b'PEkRPtcJX31w/N6Ab/bCsitHMbG0kWRoOE3i1Ums2oNTvtB/Hefytx34esbYPdGJGU5oasGl'
    b'P7C/Nvy7EYQQD0b6CLbHbeytNtTzhu82Du2TilWBAmialp+1rHtiAf+KxL8iGd209KCgA1VV'
    b'87Esb58HwN0EnhaYu5M1M2clhQpMzGQy+fizvA0UV1bs8VJZUYFi2OmaPJC1xhMAO+sjNktz'
    b'gNbgYiSxfV+Hw+XG/ZjCk0mzPOUjONhYqhNCBL89u4BBoBfoBLyA8sNnEI1Gc/P1AVVkt7QZ'
    b'6AE6zCKVFG1v3sRQKAQwAEQAw6Ql8Gben2Q9KzDeARAIBKSu6wB3ZnJOfGMeS3wBlGl8CqBt'
    b'bKcAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin82 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAqUlEQVR4nGNgGAWjgEiQlpYW'
    b'v3rP/f/1S+/+R5djJMaAa9eu/a9a/JLhEoMkw7dfHAwvehXg+piIMcA+spZhw4UvDPe45RnU'
    b'nu0l3ukYwHD6fwa7pSjeIMoFDAwMDCwaif8ZWNkYGJS0GNjqP/7nMS35T5IBf27MZzS3lmRg'
    b'UFFnkHn9lMFWX5o4jVeuXIE52ZiBgUGGgYFBkYGBgYVYixmSk5Mxog4ZAAAS/y3BHn+u4gAA'
    b'AABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin83 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABOUlEQVR4nK2Sv0oDQRDGf3sX'
    b'MMgVaiMEm9jb6JP4BmIjWNn4AnaW1goi+CTiC1gIYpE/SLwzl2QvGqOXc2ctPMLlcsYE/GBZ'
    b'hpnvm/lmF/4Tl1fXdlGOkw0C/5kL/3whkVI2MMZQaz1ycLdvO2jCr5CbnVs1t4CIoa4adI0m'
    b'DHqEQcTaacXKwEFtD9G7vSmx3ARCXZqEvkYHfYhKyEBBorD3ZVbP1i2eAdc29F63WmzhqUnS'
    b'EYhc7JuCxAHPoDwDnoHYQR+2q79aSLoCfRc7cGGUkpcFffRSuIspCz+dXSgL0Ulr5gILLejj'
    b'4E9SFhP/QMQU1SwtMIHk8xvAChADr+mJgXHhlIUMqkAlLXYAm94fwCcwAiT3CmPhzZTcBnzg'
    b'Pdt1hgUDsAU8ALUiQh4TS7TWAoRAMg8Z4BuXypfXpudBFQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin84 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAqElEQVR4nGNgGAVDAMjPt+eo'
    b'vVDxH5c8CzGGXGG6wmCyy+z/0/uvGL6//MXwoe4ZI0yOEZ9GGFDeqvL//cPPDP/eMDMwfGVm'
    b'YBD8w8Ao8IeBQegfcS549+gTw/+3LAwMX6Cauf4xvM94zUi0F/6/ZWFgYP3P8KHrMVEupimQ'
    b'YGBg4EIWIMVJMgwMDMoMDAyfGBgYPjIwMHyBYqKALAMDAysJlqEALnySACLlLfukVl0zAAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
pin85 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABMklEQVR4nL2Ru0oDQRiFv6zZ'
    b'WVFEC1GsTQpF8wCC+haKzyBiK4Ii+AQi1iIIoo1FnkDF2mvQaBaLzG5hUiSbxqxmxmYTVnPZ'
    b'xMIDU8ww5/vPmYH/1OHRsf6zeXtnV98/PDYBYlGm/JuNIyW2bXOeTpOanfnhif82bWxu6eGh'
    b'AVzXJXN3gyMlxWIRrVTLIXGA1bV1nZqeoux5lMolss9ZHClxpOTT91G1GsKy2gMO9vdiS8sr'
    b'enxsFNdxkHlJxfPwq1WUUphCYArRHgBwdnrS6Da/sKj9QqFhFt0Awrq6vGjAEomkNi0L0Qsg'
    b'rFzuNfzqTd9oRAGiFJmghQzABPqBvk6AGJAEJoLL9fhzwBdQAZ46ATTwEiwDGAzOzSD5LaC6'
    b'raCCiQDXwAjwUe/TqyaB9/rmG/h8bY2NeFVqAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin86 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA5UlEQVR4nO2QTWrCUBSFv9c8'
    b'jG8LDooQSLsHF6BUuoJO25I9BERwF9ZtKBG6BIV2UmhMHDjwhxaH0Th5HVil2L4kE2c9cOFe'
    b'Dve7nAv/Or88z9NZ/oXJaLU7d7fNprYsK/OA/Dn4vu/YJTuKo4jnoM9yvuCyWs0H9LpP+mP9'
    b'yWqx4nXywjSO2W42SCkzl4+A+8cHAVBv3OjZNGaXpkgpscvlYoCDhsFAHHrXvdK2UrkA4xPD'
    b'8F2MxiNh8nMBBv0Cmr5UARxAqX2MGpACb0BSBDD/LoQQACGgTpehQIQkSQCugdlf/hfMgT0Z'
    b'XC+h4AAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin87 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABb0lEQVR4nM2RvU4bQRSFv7nr'
    b'XSnOWkjQUUQi2O6oso/AKyDhwu9DBa4swWukoCFCFmlSUSAQiiJFsgGLYr3rtS2GXZtLYYP8'
    b'A07S5UinmXu/M0cz8F+rWq3uNZtN/Wew0WiotY/a6UQaRbHGcVfr9frfBVUqldI02O0mmiSJ'
    b'JklPa7XaQoiZPzg5+aZBEGDMeGzM2AAihna7TbFYfOVy8wFB8GUKUnr9PsPhEFXFdV2Oj89m'
    b'9hcCRByMMVhrebCWLMvwXBdxHEajEb7vz+7PB1xf/yZNU9I0JcsyPubzFAqFsX2f09Ove0vf'
    b'ACAMO9ofDBARCr6P53mICK3WHaXSxgyz0ABgbW3VHB0e4oggIogjhGG0AP9RrZtbjeOuXl5e'
    b'vXzfJ6AMrAMrgPdmgxcd7O/zYC3lcglgewK6U84trXRx8VM/5HMUNz/vAAOgP3Fv4vulDba2'
    b'yub72Q8AZ3LjE3AO/ALul7GvCsNIgd335s/kkph4P9NvLgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin88 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABeElEQVR4nO2RMUsbYRzGf2/N'
    b'HcFioETPBIRoh3bJ4HXSIyJkEg7FfICsl88RsFO3xEAhaymhFDJF9AsY2qaYDIYKBV0EC5rc'
    b'cPjmfS94HaIFxcGupT94hv/y8Dz/B/7zDyJu9WRiD+54vV6/llKSz+dRSnH4pcN6bpUwDGk0'
    b'Gmit0VpTLBZxHEcIgH6/H3W7XbTWZBYzKKX5enTM1kaeZDLJ3v4BZ+eXvMrMk81mkVJSrVbx'
    b'PG+SoN1uI4Rg6eUSV5dXKK1YW7H58P0N07/esTA3w010g+M41Go1lFLYto0O9aRvpVKJUqkU'
    b'pmkSBAGj0YggCBgMBriuSxRFNJtNDMPAsixM08Sat+h860wMWq1W9Pz1KqnZF3zefYuUkvF4'
    b'TG4tRzwexzAM/KFPr9fD930SiQTL9jKF7YJ4BuC6rjj89J6L05/MZrJ8XNhhOBwShuG9D6fT'
    b'aWKxGOVyeaqwXRB3sz2K53nR5tbmnwQnP04olUp/NfGT+A1qspC1q9A2lQAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
pin89 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACDUlEQVR4nK2RXUiTYRiGr+l+'
    b'YKRsY425H23OXBBEgUIURkY4WGfG8ExLDYqlCzqokyzpTyYEq7FAK4qICAIpWEQHI7KDwB1U'
    b'roUoBmW0mfbZBtty1duJW84VweiC9/C+3vt5HvgfBAIBqdxsBYC9waEZexASZQuMRgPRaIzz'
    b'Fy+JZDJVJFqIR0WX97RmevaDWPIh7I6tpR95+o6LnkN9YnFREtua9woAz6DvWHh8QpwauiqW'
    b'fIiOzl5x8syQuHzjvgBk+awcwG63kc0us7/jIHKFnJeTMbGl4hbOE8MYDHp6swcY0F1jpjlM'
    b'+749ZkAPfGa1ye/3F6pVadczF1+gZqKfJ8pubo5cwdbYxPzHtw5gGfgKSIUdrEYmk5FJSdSb'
    b'dExvOscF2x1CoceMBIepa2ieAtL5cIlAo9FgNpuxWq2oVCo+fUkxV2Olvt7G68k3HD3Sxej1'
    b'24mSKwB4vV6ZRqsjmVNhsVgwmUxUiRStnhlX+OkzNtTVotdricfnGRj0FcaVF/VXVOPctRG1'
    b'Wk06ncbtdhMMBhW1VjNKpYq798bIZL4x++7975HXrEAHtOdyuVFJknC5XGcjkcgrINHd6xn/'
    b'8VMQi01RKVfx4vkj2Z8ESqAFsAHfV14SeAgYdra0JdZVa3E5W/H2H1YCubVHyGMEuoDOlVZ5'
    b'KoHdTdvbBLADMP1N8C8agc3lhov4BQA4slBOiAkfAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin90 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACK0lEQVR4nNWSTUhUYRSGn+/O'
    b'Lw4qCWbkjcCFixZabWwTRRJCIVS72hSzCBGCghbWQkdxNoKbqEVB7SRSiiAoWjgz1WhMBDlF'
    b'gjRoM+JM428512n0fvf7WohDZrtWvcvDeZ/DOeeF/17ib8VUKqXr6+vRWqOUQkqJ4zg4jsPK'
    b'ygqBQADTNAWAe8skpdSlUglpSxzlsLq6ii1tpJTYGzbWmsXk50k0mvzbO+Vhxm8AXC4XXp8X'
    b'v99PVVUV6XSahYUFisUiPp+PmRd9GMLAs3v/TsD9q348fj9aa+7OVKC1pn+kh6bmZmr27MIQ'
    b'Bh9PvUYYgkfppzsBYz88oEEpxXT0NkopqisrGfvwiiMDTQghWJw4jF2Y53H4K/F4fLR8g1gs'
    b'pj0eD9+Xl3gSPo9R9wWtL3HtdBdvUjFeBuMYhsH7iXk+ZW9yr7aBs2faW7d9oVAoaK01FyKH'
    b'sNYcclMW04lFBq8MMpJ8SLo0zTm7g30NTQSWntFxY0hsW2Ggsw5huDn+rZ/uthlGLycJBWqo'
    b'eN7FyXcZhtqjHGi7CEA+bwEcBWrLgIIFWmsA1ktQ7XOxUSqSX96Lu/HYptH6CcDBE0FaWlpa'
    b'AbEFED0P5pD2OgCJ6w1gCFwCNCBTUQAai1MARCNREolEHzDvBgiHwyqZTJLNZgFB560EljSQ'
    b'wovXthDOZt7Gx8fJ5XIMDw+Xb7cjyr29vdo0TYLBIKFQiNnZWZRSZDIZMxKJzP3Z/8/6BTCo'
    b'+pErhQ5aAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin91 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB7UlEQVR4nO2ST2yLcRjHP++6'
    b't+3absuCBgcXu7gRh0kI1gMSWRYiQ3YgiBJXCYmLyyKRjISMaAQRJCxLBHGQEKngXcWSWrFi'
    b'm1ZHa9nK1vff723fnwtjjIiz5/g833zyeZ488L+UPw2HszlpWza2EJR0g+VNS3/Jzwj4UPgo'
    b'XVdi2TbfAEI4CCEQjsP8SxcobNuFYZrTAa/fDEpVVeHgAcyOowyPFCgZNrqo0BjdQvZ4F7pp'
    b'UnEle3e0K1MG/amUBFBVL2WPj/HiJyoSdFMwd3MLydhVDLuMLspcHqljweJlzPLBxVWKMmVw'
    b'pueOTPdpRLbuxsr0U1/fgOm4lCyBbjvc7k1hr9zDmFmNF3iwUflu8CgvZVmC40JQhVoVJgRo'
    b'6QyZokXi8VOedG6n8XCCl4eWTFt7piP6z2vvzNyESd6o4v71YwRXrGd0zEF/28N4YAMhj5eA'
    b'R+X9kbVzfgT49sU/W2dzDYisS2+0jc7uJEktzOCkhlvrxQ2HqSp24PdUo59qawVuKIDS3P3K'
    b'9bkKIdWHX5ZRZm9iobjJ3RdDzAvGGUifZCAwyrqwxq2Hz3Cv7KwDJn9WDwKRyOmkXNOVkNee'
    b'23J1bL9sPRGX9/papL/9nASa/+qRvvbDSlMsH1pUgz5k4MajNYD1m/y/1xfF3OVoU/d6vAAA'
    b'AABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin92 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACEUlEQVR4nNWRS0hUURyHv3vv'
    b'2Gi+kpkhxchMsAID6bWINgWJix5URBBBURDowl2boDAMalMuIqIn1SLo4TKoRVZCtogobKGJ'
    b'j9FpdHQevmbm3nvOuXNaJQoj1LJv9198H7/Dgf8eY+kRjU7qeVvgM01M08SyTCzTROscSnlo'
    b'7V2pq61pXzFgnH2uRy7v5puxlompJL9GIxytX41UHkp59PWPYBjQ/tkice+IAWAuDZQVmCjP'
    b'IzGb4e3XMfbXrwEMDAy6ZkrJOi62I0DJRWdZoLzIRKkcqbkMfpGlwvIAeDoqwZUo6SKli5NK'
    b'LTq+ZQv8BtJT9PeNc67BT2RiGiEV9z/ECZWW0xJyuT0cpHlDmlf5FgyOThOdjHN8k4UrJEIq'
    b'hFTotI0zb6OES2ZmnoZqK/+CoRsHEUIReNTBpFFIR/Femjb60QsO2TkXVekisn605+X/hfBm'
    b'9KqKAFW9CQb2rCdtC5yZBD/aX2I7glhkkOKyAJ2xdczdPNwIDC8Gjj3cqs8XnKGwZjv4Sjj5'
    b'IsyD5iIWpJ+Bsi1MJOME+7u5O1ZNa900JVU+Lpxu2WYAdL1+rytDpbQ928edUx8JBoJkHZdI'
    b'+CfxhRyu0jiOIDo+xHDfJ6YOfIfHtbt6enq+LHvCH9509+qp5CzpjM27oWvEzAF2Jk4QHo+y'
    b'o+kQl9paLSCXz12R67ee6ItXOxv/SfobfgNaIfOnr1k4NwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin93 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACOklEQVR4nMWS3UvTcRTGP9+f'
    b'228vos45zZW4Gb5AkZAG3YxqFay3i6I31PRvMLoIgm6ioKKrsKuIrNEQghbRy+Z9kdZKVOpC'
    b'FMIJ0maTNvd1W7/ftwtBkrS667k85zzPec7Dgf8NsVEjGn2iSqUStbV1FAtFQodC686uFuPx'
    b'uEomk+TzeTweN2VlFnRdx6FbCR05tuEiATDx8b3KZr9TKhnIZYlAo8LlYnxikkQiQSaTQUqJ'
    b'YRiLsVis+lcBC4DVasG2PE5xfgqfv52pxVpcmiA1P4erohyLUNR4mtm+o90VCARUY6OPvr5e'
    b'seogMfJapaaiNLV0YPxYwuNtI5dXfJjOcjjg5154mDNd5+jp7sJpt/HiVQzTNAWAtqIi0GzV'
    b'jH2axe1tQ9MVM990Ov1NWHUHQghkPs+Nm7cwEQgh1p6gUGh2N7tavCzMDFPt3cbg82nqt2zl'
    b'an0NSimWpCSVTv8W4oqAgrejbxh/meHk6TocppNLO4s0h5pRhsRUimRyDqfTub5ALpflxF4f'
    b'5VWdOCvcWJyVMHcerbAfVdmIab7j4f27ZHNZDMNA13WklKxmYNFtTH5t5XIkjb28EqvNztNs'
    b'P1hBFFMYhsHR46d4FHlMsVTC7/etOtAAAnuC4mx3n7ac/DwYHylwJzyGo6rAbFqAvgnDNDkQ'
    b'DDIUfUbH7iANDZsBWgHLhh8GuMPhBwujoyNIKZFS0n/hItevXcFmsxGJDO0DvvyBvwYacHBg'
    b'4Lbq7e1RQPe/Ev+Kn86G2m3gsZILAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin94 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABtElEQVR4nO2ST0iTcRzGP+8c'
    b'c7E5h9JBgiQSEtQgEKSD0KWDF09WUkE1EET8A3bsUkR3L+pBvIgRQSBqVNShQkgNqsMycvKq'
    b'W+aUanvX9v62vb/f+/46pV0KO3Xpc3rgy/Pw8OWB//x7jN8ddna/atfzUMpFKoUjFd+yOdZT'
    b'6VtXznXc/GNAYs3UougQrgqjlIsj1V7IT738Js6NoWuG71fj5UfaGo1ry/TVsRk8yrNshNRW'
    b'mi9nG1g1k6wkNnix8IrUmVY8JfcbXJjTlgb8Pmio9YygEhFJiepDlSxkDCqVS8DwqAl4hJan'
    b'mdysI1dRgT3eVeMHuN9pRAG652X+u/DCwU/vONLSguVqRL7ElgqQXX1L2iowEJXk7SL3nlxl'
    b'vqcnufeDD4kN/brpGK1xE6lclFS8dOuZmptlZPIiorkN8/x1tpNrnHj6kNjSYggQPoCVj6Ye'
    b'HuxDA6X+ToQoEhrs4KT9njvt9WQmnpPrvU00UsXn1PpMbGnRAASAH6Cp8bgBcOnBY505XItn'
    b'CwqJJPmCTdlROGVJQRQZiHUFgfJBNxKeuDurx6Zm9Km2090HNf01PwDm19ObL3375QAAAABJ'
    b'RU5ErkJggg==')

#----------------------------------------------------------------------
pin95 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACDUlEQVR4nMWSPUyTURiFn3u/'
    b'D9vSflQwJg66mJTAJDHEwWg04mBijDK4OLi4OOmgbkaNRiPuziQmTEYwxIBVI3FAFBPiICTC'
    b'ICpoUSi00D/un0NLK8bG0TO9uTnn3Peec+F/Q/yLMHvlkovu3AXO4QCcK8/Wsr6arW8wf+um'
    b'a4jFaoKyGucc4Jgb6KextR3/T+H3nrtOeh4OsFrXDCq3zw8+BuD1SoajUDNI3etxVEhW68qp'
    b'A+swSpFKDiODgJbjp9hz/Sq3WxMASIAPZ8+4d733KWWWWZqewhmNNZrc7CzzTwZJJYd5trRS'
    b'3XJkX2d19gE+T4wRDpr4Oj7Ky+lpup9eI3vxHH4mhxACIepnLQHCsSYiTc2oQoEHi1kAdKmI'
    b'VhqlFFpprDWVIDfDB/DDEUKxgFz6J+cTuwFQxTxOWYQAISXGGLTWlRbKmMmslg2yqTkKK2nW'
    b'i3ka2zoAWM/ncMpHCIGUEqPLBtYYrLXs3xqnc+BRrw8QCuKEojFynxZ5O/6Gg0ApvwZEkRsG'
    b'1mKMoe/9FJOR7TwcGWoBln2ALZEo4SAOwKtMjsuVP6CdQgiJ50lmCgWOpNPcGB07CQxuykBI'
    b'iS4VAbjQlqi+USmFlBLnfD7uPUTX834PsL+HuNFPR/uBYy/ufJvY5jX4fOnq5vDaMpNDSaTn'
    b'cXrhxw5g4W811iu4GTgBGKCvDgeAX+EJ+BBMDpF/AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
pin96 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABwElEQVR4nLXRP2hTURTH8e95'
    b'tHYJGYqL1D9gtFQQumZ0aQb/TMEuNuqeMWMgo0MISMApEkIQFIpjg7MmU8CxIcVBUpfWwjOB'
    b'9x7v3ffnOIihzxQMiAfucC/3fO7vcuB/VC53494/AZ1OR5e9a110OJ1Ol35sAegP+uo4Dq7r'
    b'LpUiBXiep6cnp7iuS7vd5nB0+FdEzm/CMFRVZTabMT4as7qySj6fl3q9rmEYUq1W5U8glUBV'
    b'6R18JZPJ0H/7CgSazaaqKqpKrVZbSJQCRqMRtzdDVJWN/H1EBGMMSZKQJAlxHFOpVFJIKpLj'
    b'OPrp4wk3cxH2D5tBf0CSJERRhDEGYwy+7+N5Hq1Waw0w8wS2bauIcDS2+X52hohQLpcJw3C+'
    b'jDHsFAo83t0FuAZcmgOWZRFFEU+f5xARRIQgCCgWiwRBwNadLdb0CnEc4Qc+wLdUAsuyEBGS'
    b'JPkFIHx+vQ7ATqHAu5fPuH63QBTFPHrwUAADsPIbyGaz4jiOvv9wme1bXxARjo/hqgiBCXhS'
    b'eUNpb3thjHOg2+3qZDIhvxnhq7C/v8/6xov5V0p7pYXmhSkA9Ho9HQ6HuK5Lo9G4sOl8/QTp'
    b'Mdw6prCAqAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin97 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACKklEQVR4nNWST0iTcRyHn/dV'
    b'm05XaYMiUmpo6iYSCZFEKmZEo0OXKKU/ZJHdoijoGEXdNekgJER1MP9gGWF0EsKVEVMzsaUW'
    b'9EdSD9tsMqfvPh2WgqV07nf5/A7f58OXLw/898/410BgO5qag5gFsXk48GM5Y/4JLOxELXWn'
    b'FCxG391oXmAJJBDQmYkA/PWJTF4Ee3JQ0xcDyxflMDASuMLU1DSO2gokiAvi8USGA49kGF0M'
    b'2x5+MgEuG4ZKR2M0R6NIQhK5LheS+BYEKw6WlciqvlYMo4uMdX7c5+PbAIjFYnrT/15vB4Zl'
    b'WZaedb9QS1uHvF6vIpGImkz01InCgXbNfDwuTRZpYmJCSzeQxEZnFmmpNupv3yEUChG34nTv'
    b'uEi6t4WFSycoewCG0UG63c/nSBemabKswJ5qI9W2hoKCfPZX7cNdVMyNzGGMQidHy++Dq4aM'
    b'9YN8mGnDTDKXCpIXCwYG+il0e8jeksPY+DizcxZ5efn0Vm4lxVHN5NeXjM0+xm43STKTFgty'
    b'kwHC4Z80NNQTCoWIRqMcqznJ3rIKZqMx4rEge2ozGPI0ohE/o3fLaH/u48KZI1lA8C9xSkpK'
    b'5PF45HK51Ot7LafTqasHs0TVPRl1T0R5s4AcoADYsKqJvld9Kt29y3A4HLp1KI3A5rM0jhbB'
    b'pgw0Mg09tatbPPhuSL+/aUApkE1Ce49R3ZrYBFJWhK9dvyngNFDJCqoDNuNcp4C1gOsXGXD6'
    b'jqoOerwAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
pin98 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACDklEQVR4nMWTQU8TQRTHf7Od'
    b'jQ30UNAD3ZaFitEiGIVEQm98BPkgwh0vHrn3DH4Er2JMvVgvEo1GCW5NS9SC0GVF26Vsy+7z'
    b'QNiImBBP/i8zb97//TLz8gb+t9RFhlKpJJ1Oh+PjY5aWls75zx3s7e2JiFAulzk8PKTdbhME'
    b'Ab1ej263SxAELC8vx3XG6aZSqdyrVquy7+3jei5zc3McHR3R7XaJoggRIYoioihiYWFBzgCa'
    b'zab0p/ofh2HIs7WnLN5fxHVd5ufn46IwDOM1DEPW19clfkKj0ZDfTclkEgARQRBWV1bp9XpY'
    b'loVt2wzbw/i+T3G2qAyAbDar6o0mRsJka2cXrTWe51Gr1XCqDunBNCOjI0xNT5HJZNj41MA0'
    b'zbM9MAyDdxsOn79s4/s+fX19fHU72Dmb1JU8kxOTvH5fRylF2RjH1H8Atr+5XB4cIJHQuGt5'
    b'3j66CsBO/xgAWmt2h4soQzG+Mo029VnAqbQ2carw88dJvPvheQwYKl1DKcXsgyenN0idAyQS'
    b'mqwFvn+SaqtsDKjfeYjneXz3XFKpFAcHBy0DIAgCERE2aw1uF8Z48WoI3xsAYDTZigGTN2wm'
    b'bk4wc3cGy7Iy6XRaxRPl+76ICI7jkM/nqW/V+bjlcj1v8fLNJsVbo2hTk7yUpFAoJIAonoO/'
    b'yXVdiaKIVquFaZoYhkEul7vw7/yzfgEoSfZhdd2tPgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
pin99 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACQUlEQVR4nKWSXUiTURzGn7O9'
    b'cxKVc13Mml/ly7DWhw01pEYGetMsyT7HKuoqMOouwovVTTrIWnQjin3dlF2Vg5lYUO298GNK'
    b'GY0kVszNcowcTY3Z+24v/27aGugLRQfO1f95nvM7zznAfy4GAMG+OlpdUo+fmmIUGUuQbzyg'
    b'YozRPyUJHwNUd+0FjXdt/ivjt4bGP7rpAQfJ82MUfuagydvraGnmsWLIxLspGj16JDtnAGDu'
    b'HKFEbB7xSBQpfR7kbgdTCrh6676uqdb8vaDIAFNFGcsK7/Y6KTY1hN0VKeQPV0Jz2QnL9i3Z'
    b'+ZXOnpCclstrLVsx9iaAjrZWliUAADHqpVn/PcjJL+DtfiZJKXK2u3H88EEkl0R8Cs3gQzAE'
    b'NcclXG2thRkfp1jSXByn7C2Yjc4hFP4KmQjXnReXXU21kjkcmSVXhwvhSBTxxDx0ujWo31OD'
    b'm92PqOvOw9CKJ4pRL4U8LdQ/+JqGXg7T81fDuS9Bexubq/qeDp4Rdmyjz9MzZLPZqOF8wYJi'
    b'ByuQcpUni02VP6rf8zwPu2EDAqWm5R0QkZzph+d5tdFolH0+X9pyziCWxqohSRL8fj9uCAJT'
    b'7ECr1W7U6/VFoigWa2reLni9XtoUt0KlUiEojUAQhPKMN0OQg8xUoiiutRxiEzv1Jzi1qIbH'
    b'44Hb7caxdjOCTxZZrj5DQGqtDkzNYV/v+EDDpbzJqsKzXDqdRjKZRCKRwOne/U2jPYsZI/3e'
    b'UPyyu5rXU5nWilXWfjy4ICnqfgGpNPd4KQ1qOQAAAABJRU5ErkJggg==')

